# Data batch processing

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy
import os
from scipy.stats import entropy
from concurrent.futures import ThreadPoolExecutor, as_completed

/Users/jasonc/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
consumer_df = pd.read_parquet("/Users/jasonc/Desktop/DSC_291/cashflow/consumer_data.parquet")

In [3]:
consumer_df

     evaluation_date  FPF_TARGET  total_balance masked_consumer_id
0         2021-08-26         0.0        1380.84          C01100001
1         2022-08-02         0.0       20163.90          C01100002
2         2021-03-04         0.0        3986.25          C01100003
3         2022-11-19         0.0        5956.03          C01100004
4         2021-11-21         0.0       29421.10          C01100005
...              ...         ...            ...                ...
4995      2023-03-31         0.0        1412.80          C04104996
4996      2023-03-31         0.0        -439.21          C04104997
4997      2023-03-31         0.0          84.53          C04104998
4998      2023-03-31         0.0       52655.88          C04104999
4999      2023-03-31         0.0       40004.69          C04105000

[16000 rows x 4 columns]

In [4]:
# FFT Feature Function
def extract_fft_features(ts, detrend=True, low_freq_cut=0.05, high_freq_cut=0.25):
    ts = ts.asfreq('W-MON').fillna(0)
    if detrend:
        ts = ts - ts.mean()

    fft_vals = np.fft.fft(ts)
    fft_freqs = np.fft.fftfreq(len(ts), d=1)
    pos_mask = fft_freqs > 0
    freqs = fft_freqs[pos_mask]
    mags = np.abs(fft_vals)[pos_mask]
    power = mags**2
    power_norm = power / power.sum()

    if len(power) == 0:
        return None

    dominant_idx = np.argmax(power)
    dominant_freq = freqs[dominant_idx]
    dominant_power = power[dominant_idx]
    spectral_entropy = entropy(power_norm)
    low_power = power[freqs < low_freq_cut].sum()
    high_power = power[freqs > high_freq_cut].sum()
    power_ratio = low_power / (high_power + 1e-6)

    return {
        "dominant_freq": dominant_freq,
        "dominant_power": dominant_power,
        "spectral_entropy": spectral_entropy,
        "low_freq_power": low_power,
        "high_freq_power": high_power,
        "power_ratio": power_ratio
    }

In [5]:
def weekly_trimmed(ts):
    ts = ts.groupby(ts.index).sum()  # collapse duplicates
    ts = ts.asfreq('D').fillna(0)
    if ts.empty:
        return pd.Series(dtype=float)

    first_monday = ts.index[0] + pd.DateOffset(days=(7 - ts.index[0].weekday()) % 7)
    last_sunday = ts.index[-1] - pd.DateOffset(days=(ts.index[-1].weekday() + 1) % 7)
    ts_trimmed = ts[(ts.index >= first_monday) & (ts.index <= last_sunday)]

    return ts_trimmed.resample('W-MON').sum()

In [6]:
# Consumer Processor
def process_consumer_file(file_path):
    try:
        consumer_id = os.path.basename(file_path).replace(".parquet", "")
        df = pd.read_parquet(file_path)

        # Safely convert to datetime
        df['posted_date'] = pd.to_datetime(df['posted_date'], errors='coerce')
        df = df.dropna(subset=['posted_date'])
        df = df.sort_values('posted_date')

        if df.empty:
            raise ValueError("No valid posted_date after cleaning")

        # Resample to daily and fill forward
        ts = (
            df.set_index('posted_date')
            .resample('D')['amount']
            .sum()
            .ffill()
        )

        if ts.empty or ts.sum() == 0 or ts.std() == 0:
            raise ValueError("Time series is empty or flat")

        features = extract_fft_features(ts)
        if features is None:
            raise ValueError("FFT failed due to empty power spectrum")

        features['masked_consumer_id'] = consumer_id
        print(f"✓ Processed {consumer_id}")
        return features

    except Exception as e:
        print(f"✗ Failed {file_path}: {e}")
        return None

In [7]:
def process_consumer_file_by_category(file_path, consumer_df, n_simulations=20):
    """
    Reads a single consumer's transaction Parquet file, computes FFT-based features for each category,
    and if the consumer's FPF_TARGET is 1, generates `n_simulations` noisy augmentations.

    Returns a list of feature dicts (one per real or simulated consumer)."""
    consumer_id = os.path.basename(file_path).replace(".parquet", "")
    match = consumer_df[consumer_df["masked_consumer_id"] == consumer_id]
    if match.empty:
        raise ValueError(f"Consumer ID {consumer_id} not found in metadata.")

    target_value = match["FPF_TARGET"].iloc[0]
    is_target = (target_value == 1.0)

    # Load and clean
    df = pd.read_parquet(file_path)
    df['posted_date'] = pd.to_datetime(df['posted_date'], errors='coerce')
    df = df.dropna(subset=['posted_date']).sort_values('posted_date')
    if df.empty:
        raise ValueError(f"No valid posted_date for consumer {consumer_id}")

    results = []
    ts_by_category = {}

    # Process real data per category
    for cat, sub_df in df.groupby('category'):
        ts = sub_df.set_index('posted_date')['amount']
        ts_weekly = weekly_trimmed(ts)

        # Skip invalid series
        if ts_weekly.empty or ts_weekly.sum() == 0 or len(ts_weekly) < 6:
            continue

        ts_by_category[cat] = ts_weekly
        feats = extract_fft_features(ts_weekly)
        if feats is None:
            continue

        feat_dict = {f"{k}_cat{cat}": v for k, v in feats.items()}
        feat_dict['masked_consumer_id'] = consumer_id
        feat_dict['FPF_TARGET'] = target_value
        results.append(feat_dict)

    real_count = len(results)

    # Simulations for target consumers
    sim_count = 0
    if is_target and ts_by_category:
        for sim_idx in range(1, n_simulations + 1):
            sim_id = f"{consumer_id}_simulate_{sim_idx}"
            sim_feats = {}
            # generate features across all categories
            for cat, ts_weekly in ts_by_category.items():
                noise = np.random.normal(loc=0,
                                         scale=ts_weekly.std() * 0.1,
                                         size=len(ts_weekly))
                ts_noisy = ts_weekly + noise
                feats = extract_fft_features(ts_noisy)
                if feats is None:
                    continue
                for k, v in feats.items():
                    sim_feats[f"{k}_cat{cat}"] = v

            # attach metadata
            sim_feats['masked_consumer_id'] = sim_id
            sim_feats['FPF_TARGET'] = target_value
            results.append(sim_feats)
            sim_count += 1

    if not results:
        raise ValueError(f"No valid features generated for consumer {consumer_id}")

    # Log processing summary
    if sim_count > 0:
        print(f"Processed {consumer_id}: {real_count} real entries and {sim_count} simulations (FPF_TARGET={target_value}).")
    else:
        print(f"Processed {consumer_id}: {real_count} real entries (FPF_TARGET={target_value}).")

    return results

In [8]:
def batch_process(tx_dir, consumer_df, n_simulations=20, max_workers=None):
    """
    Processes all consumer files in parallel, flattening real and simulated feature dicts
    into a single DataFrame."""
    file_paths = [os.path.join(tx_dir, f) for f in os.listdir(tx_dir) if f.endswith('.parquet')]
    all_dicts = []

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(
                process_consumer_file_by_category,
                fp,
                consumer_df,
                n_simulations
            ): fp for fp in file_paths
        }
        for future in as_completed(futures):
            path = futures[future]
            try:
                res = future.result()
                # flatten list of dicts
                all_dicts.extend(res if isinstance(res, list) else [res])
            except Exception as e:
                print(f"Error processing {path}: {e}")

    return pd.DataFrame(all_dicts)

In [9]:
if __name__ == "__main__":
    TX_DIR = "/Users/jasonc/Desktop/DSC_291/split_transactions"

    # Run batch processing with simulations for target consumers
    output_df = batch_process(
        TX_DIR,
        consumer_df,
        n_simulations=20,
        max_workers=None
    )

    # Save the engineered feature matrix
    output_df.sort_index(axis=1).to_csv(
        "/Users/jasonc/Desktop/DSC_291/processed_data.csv",
        index=False
    )

Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03104720.parquet: No valid features generated for consumer C03104720
Processed C03104658: 13 real entries (FPF_TARGET=0.0).
Processed C02104921: 16 real entries (FPF_TARGET=0.0).
Processed C03100574: 15 real entries (FPF_TARGET=0.0).
Processed C03103766: 15 real entries (FPF_TARGET=0.0).
Processed C03102314: 12 real entries (FPF_TARGET=0.0).
Processed C04103556: 17 real entries (FPF_TARGET=0.0).
Processed C04104510: 26 real entries (FPF_TARGET=0.0).
Processed C04104468: 10 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03101106.parquet: No valid posted_date for consumer C03101106
Processed C04101336: 14 real entries (FPF_TARGET=0.0).
Processed C02100394: 15 real entries (FPF_TARGET=0.0).
Processed C02103186: 24 real entries (FPF_TARGET=0.0).
Processed C04102124: 18 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03104648.parquet: No valid features generated for consumer C03104648
Processed C01102837: 20 real entries (FPF_TARGET=0.0).
Processed C04104500: 14 real entries (FPF_TARGET=0.0).
Processed C03104730: 6 real entries (FPF_TARGET=0.0).
Processed C04101326: 19 real entries (FPF_TARGET=0.0).
Processed C02104931: 17 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03103776.parquet: No valid posted_date for consumer C03103776
Processed C01102827: 21 real entries (FPF_TARGET=0.0).
Processed C04103546: 19 real entries (FPF_TARGET=0.0).
Processed C04100754: 19 real entries (FPF_TARGET=0.0).
Processed C03100564: 20 real entries (FPF_TARGET=0.0).
Processed C02103196: 15 real entries (FPF_TARGET=0.0).
Processed C04104478: 18 real entries (FPF_TARGET=0.0).
Processed C04102134: 19 real entries (FPF_TARGET=0.0).
Processed C03104994: 7 real entries (FPF_TARGET=0.0).
Processed C01102683: 18 real entries (FPF_TARGET=0.0).
Processed C04104345: 19 real entries (FPF_TARGET=0.0).
Processed C03102304: 22 real entries (FPF_TARGET=0.0).
Processed C01103389: 24 real entries (FPF_TARGET=0.0).
Processed C04102609: 21 real entries (FPF_TARGET=0.0).
Processed C04100069: 20 real entries (FPF_TARGET=0.0).
Processed C04102771: 20 real entries (FPF_TARGET=0.0).Processed C03104175: 6 real entries (FPF_TARGET=0.0).

Processed C03101116: 22 real entries (FPF_TARGET=0.0).
Processed C01100802: 23 real entries (FPF_TARGET=0.0).
Processed C03101753: 9 real entries (FPF_TARGET=0.0).
Processed C01101491: 11 real entries (FPF_TARGET=0.0).
Processed C03104984: 3 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C01102693.parquet: No valid features generated for consumer C01102693
Processed C04100079: 21 real entries (FPF_TARGET=0.0).
Processed C04101573: 19 real entries (FPF_TARGET=0.0).
Processed C03103133: 20 real entries (FPF_TARGET=0.0).
Processed C04102619: 21 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03100249.parquet: No valid posted_date for consumer C03100249
Processed C03100259: 21 real entries (FPF_TARGET=0.0).
Processed C04103313: 16 real entries (FPF_TARGET=0.0).
Processed C01103399: 21 real entries (FPF_TARGET=0.0).
Processed C01101481: 11 real entries (FPF_TARGET=0.0).
Processed C04100898: 8 real entries (FPF_TARGET=0.0).
Processed C04102761: 17 real entries (FPF_TARGET=0.0).
Processed C03101743: 12 real entries (FPF_TARGET=0.0).
Processed C01100812: 12 real entries (FPF_TARGET=0.0).
Processed C03102551: 18 real entries (FPF_TARGET=0.0).
Processed C01104930: 16 real entries (FPF_TARGET=0.0).
Processed C03104165: 20 real entries (FPF_TARGET=0.0).
Processed C03102429: 15 real entries (FPF_TARGET=0.0).
Processed C04104023: 22 real entries (FPF_TARGET=0.0).
Processed C04100277: 5 real entries (FPF_TARGET=0.0).
Processed C03100047: 19 real entries (FPF_TARGET=0.0).
Processed C03101435: 8 real entries (FPF_TARGET=0.0).
Processed C04103884: 14 real entries (FPF_TARGET=0.0).
Processed C04103065: 21 real entries (FPF_TARGET=0.0).
Processed C01103197: 19 real entries (FPF_TARGET=0.0).
Processed C03102627: 27 real entries (FPF_TARGET=0.0).
Processed C04102417: 10 real entries (FPF_TARGET=0.0).
Processed C03104213: 23 real entries (FPF_TARGET=0.0).
Processed C01104848: 21 real entries (FPF_TARGET=0.0).
Processed C04103075: 17 real entries (FPF_TARGET=0.0).
Processed C01103966: 23 real entries (FPF_TARGET=0.0).
Processed C04104033: 19 real entries (FPF_TARGET=0.0).
Processed C03103255: 27 real entries (FPF_TARGET=0.0).
Processed C01103187: 21 real entries (FPF_TARGET=0.0).
Processed C04102407: 20 real entries (FPF_TARGET=0.0).
Processed C01104920: 24 real entries (FPF_TARGET=0.0).
Processed C02102836: 21 real entries (FPF_TARGET=0.0).Processed C03101425: 16 real entries (FPF_TARGET=0.0).

Processed C03100057: 26 real entries (FPF_TARGET=0.0).
Processed C03103245: 20 real entries (FPF_TARGET=0.0).
Processed C04103894: 19 real entries (FPF_TARGET=0.0).
Processed C02103398: 16 real entries (FPF_TARGET=0.0).
Processed C04103630: 4 real entries (FPF_TARGET=0.0).
Processed C02102692: 20 real entries (FPF_TARGET=0.0).
Processed C03100612: 11 real entries (FPF_TARGET=0.0).
Processed C04104676: 24 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102893.parquet: No valid features generated for consumer C03102893
Processed C02100813: 15 real entries (FPF_TARGET=0.0).
Processed C03102072: 19 real entries (FPF_TARGET=0.0).
Processed C04103748: 18 real entries (FPF_TARGET=0.0).
Processed C04101128: 20 real entries (FPF_TARGET=0.0).
Processed C03104446: 14 real entries (FPF_TARGET=0.0).
Processed C03101260: 15 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102062.parquet: No valid posted_date for consumer C03102062
Processed C02103967: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103568: 11 real entries (FPF_TARGET=0.0).
Processed C04103620: 21 real entries (FPF_TARGET=0.0).
Processed C04101040: 21 real entries (FPF_TARGET=0.0).
Processed C03100602: 11 real entries (FPF_TARGET=0.0).
Processed C02102682: 13 real entries (FPF_TARGET=0.0).
Processed C03103400: 25 real entries (FPF_TARGET=0.0).
Processed C04100432: 14 real entries (FPF_TARGET=0.0).
Processed C04103758: 20 real entries (FPF_TARGET=0.0).
Processed C03103410: 19 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03104456.parquet: No valid features generated for consumer C03104456
Processed C03101270: 16 real entries (FPF_TARGET=0.0).
Processed C04101138: 21 real entries (FPF_TARGET=0.0).
Processed C03102883: 22 real entries (FPF_TARGET=0.0).
Processed C03103394: 17 real entries (FPF_TARGET=0.0).
Processed C03100967: 19 real entries (FPF_TARGET=0.0).
Processed C01104989: 19 real entries (FPF_TARGET=0.0).
Processed C04104903: 21 real entries (FPF_TARGET=0.0).
Processed C02104532: 11 real entries (FPF_TARGET=0.0).
Processed C01103056: 20 real entries (FPF_TARGET=0.0).
Processed C01101636: 23 real entries (FPF_TARGET=0.0).
Processed C02103574: 20 real entries (FPF_TARGET=0.0).
Processed C01102424: 6 real entries (FPF_TARGET=0.0).
Processed C04103945: 23 real entries (FPF_TARGET=0.0).
Processed C02102106: 13 real entries (FPF_TARGET=0.0).
Processed C03100186: 17 real entries (FPF_TARGET=0.0).
Processed C01100244: 17 real entries (FPF_TARGET=0.0).
Processed C01101626: 15 real entries (FPF_TARGET=0.0).
Processed C01104168: 22 real entries (FPF_TARGET=0.0).
Processed C04103955: 20 real entries (FPF_TARGET=0.0).
Processed C02103564: 14 real entries (FPF_TARGET=0.0).
Processed C02104859: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104000: 16 real entries (FPF_TARGET=0.0).
Processed C01103046: 18 real entries (FPF_TARGET=0.0).
Processed C02101942: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100977: 20 real entries (FPF_TARGET=0.0).
Processed C02104522: 21 real entries (FPF_TARGET=0.0).
Processed C02103977: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104999: 21 real entries (FPF_TARGET=0.0).
Processed C04104913: 14 real entries (FPF_TARGET=0.0).
Processed C03100196: 20 real entries (FPF_TARGET=0.0).
Processed C01104178: 22 real entries (FPF_TARGET=0.0).
Processed C02100776: 18 real entries (FPF_TARGET=0.0).
Processed C01100254: 25 real entries (FPF_TARGET=0.0).
Processed C04102383: 22 real entries (FPF_TARGET=0.0).
Processed C04101970: 19 real entries (FPF_TARGET=0.0).
Processed C01102309: 22 real entries (FPF_TARGET=0.0).
Processed C01103603: 25 real entries (FPF_TARGET=0.0).
Processed C03104587: 19 real entries (FPF_TARGET=0.0).
Processed C03102952: 15 real entries (FPF_TARGET=0.0).
Processed C01100569: 16 real entries (FPF_TARGET=0.0).
Processed C01102271: 23 real entries (FPF_TARGET=0.0).
Processed C02104849: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104795: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101191: 16 real entries (FPF_TARGET=0.0).
Processed C02102753: 17 real entries (FPF_TARGET=0.0).
Processed C02103388: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100411: 13 real entries (FPF_TARGET=0.0).
Processed C01101073: 9 real entries (FPF_TARGET=0.0).
Processed C03104597: 19 real entries (FPF_TARGET=0.0).
Processed C01104655: 15 real entries (FPF_TARGET=0.0).
Processed C02103331: 13 real entries (FPF_TARGET=0.0).
Processed C01100579: 10 real entries (FPF_TARGET=0.0).
Processed C03102942: 13 real entries (FPF_TARGET=0.0).
Processed C02101490: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102393: 15 real entries (FPF_TARGET=0.0).
Processed C02102826: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101960: 17 real entries (FPF_TARGET=0.0).
Processed C01102319: 20 real entries (FPF_TARGET=0.0).
Processed C02101551: 14 real entries (FPF_TARGET=0.0).
Processed C04103699: 18 real entries (FPF_TARGET=0.0).
Processed C01103613: 11 real entries (FPF_TARGET=0.0).
Processed C02102743: 22 real entries (FPF_TARGET=0.0).
Processed C02101480: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101429: 18 real entries (FPF_TARGET=0.0).
Processed C01100401: 17 real entries (FPF_TARGET=0.0).
Processed C04101818: 19 real entries (FPF_TARGET=0.0).
Processed C01102261: 24 real entries (FPF_TARGET=0.0).
Processed C02100123: 19 real entries (FPF_TARGET=0.0).
Processed C01104523: 21 real entries (FPF_TARGET=0.0).
Processed C01101305: 5 real entries (FPF_TARGET=0.0).
Processed C01103565: 15 real entries (FPF_TARGET=0.0).
Processed C04102804: 22 real entries (FPF_TARGET=0.0).
Processed C02102435: 19 real entries (FPF_TARGET=0.0).
Processed C03101308: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104799: 15 real entries (FPF_TARGET=0.0).
Processed C03101826: 20 real entries (FPF_TARGET=0.0).
Processed C02104785: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104179: 13 real entries (FPF_TARGET=0.0).
Processed C04103497: 21 real entries (FPF_TARGET=0.0).
Processed C01103575: 13 real entries (FPF_TARGET=0.0).
Processed C01102117: 23 real entries (FPF_TARGET=0.0).
Processed C02103057: 7 real entries (FPF_TARGET=0.0).
Processed C04100695: 23 real entries (FPF_TARGET=0.0).
Processed C01101315: 24 real entries (FPF_TARGET=0.0).
Processed C02102116: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103487: 21 real entries (FPF_TARGET=0.0).
Processed C02100245: 16 real entries (FPF_TARGET=0.0).
Processed C01102107: 22 real entries (FPF_TARGET=0.0).
Processed C03104789: 20 real entries (FPF_TARGET=0.0).
Processed C04102814: 21 real entries (FPF_TARGET=0.0).
Processed C02101314: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101304: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104376: 19 real entries (FPF_TARGET=0.0).
Processed C03100398: 14 real entries (FPF_TARGET=0.0).
Processed C01101550: 20 real entries (FPF_TARGET=0.0).
Processed C03101692: 20 real entries (FPF_TARGET=0.0).
Processed C04100949: 22 real entries (FPF_TARGET=0.0).
Processed C02104654: 17 real entries (FPF_TARGET=0.0).
Processed C02101072: 15 real entries (FPF_TARGET=0.0).
Processed C01100122: 20 real entries (FPF_TARGET=0.0).
Processed C04104284: 19 real entries (FPF_TARGET=0.0).
Processed C02101439: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101541: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103813: 6 real entries (FPF_TARGET=0.0).
Processed C01101428: 18 real entries (FPF_TARGET=0.0).
Processed C04100831: 20 real entries (FPF_TARGET=0.0).
Processed C02100133: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102480: 7 real entries (FPF_TARGET=0.0).
Processed C01103248: 18 real entries (FPF_TARGET=0.0).
Processed C01102742: 28 real entries (FPF_TARGET=0.0).
Processed C03104855: 20 real entries (FPF_TARGET=0.0).
Processed C01103320: 16 real entries (FPF_TARGET=0.0).
Processed C04100959: 24 real entries (FPF_TARGET=0.0).
Processed C02100568: 13 real entries (FPF_TARGET=0.0).
Processed C02103321: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103259: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104998: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101637: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104366: 21 real entries (FPF_TARGET=0.0).
Processed C03100388: 17 real entries (FPF_TARGET=0.0).
Processed C01101540: 22 real entries (FPF_TARGET=0.0).
Processed C03101682: 5 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100821: 19 real entries (FPF_TARGET=0.0).
Processed C01103258: 21 real entries (FPF_TARGET=0.0).
Processed C03102490: 18 real entries (FPF_TARGET=0.0).
Processed C01102752: 22 real entries (FPF_TARGET=0.0).
Processed C02103047: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100255: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103249: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104845: 22 real entries (FPF_TARGET=0.0).
Processed C04104294: 22 real entries (FPF_TARGET=0.0).
Processed C01101438: 19 real entries (FPF_TARGET=0.0).
Processed C01103352: 19 real entries (FPF_TARGET=0.0).
Processed C01102658: 26 real entries (FPF_TARGET=0.0).
Processed C03103090: 9 real entries (FPF_TARGET=0.0).
Processed C02101062: 9 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104169: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104314: 22 real entries (FPF_TARGET=0.0).
Processed C01101532: 16 real entries (FPF_TARGET=0.0).
Processed C04100853: 20 real entries (FPF_TARGET=0.0).
Processed C02100462: 14 real entries (FPF_TARGET=0.0).
Processed C02101893: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102720: 14 real entries (FPF_TARGET=0.0).
Processed C01100140: 14 real entries (FPF_TARGET=0.0).
Processed C02102260: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100578: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103871: 19 real entries (FPF_TARGET=0.0).
Processed C03100282: 13 real entries (FPF_TARGET=0.0).
Processed C02103660: 12 real entries (FPF_TARGET=0.0).
Processed C02103612: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101522: 21 real entries (FPF_TARGET=0.0).
Processed C02104644: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104626: 15 real entries (FPF_TARGET=0.0).
Processed C01103342: 22 real entries (FPF_TARGET=0.0).
Processed C03103080: 14 real entries (FPF_TARGET=0.0).
Processed C03101798: 7 real entries (FPF_TARGET=0.0).
Processed C01100150: 21 real entries (FPF_TARGET=0.0).
Processed C02100410: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100292: 9 real entries (FPF_TARGET=0.0).
Processed C02102308: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100843: 15 real entries (FPF_TARGET=0.0).
Processed C01102730: 17 real entries (FPF_TARGET=0.0).
Processed C02104063: 11 real entries (FPF_TARGET=0.0).
Processed C03103861: 24 real entries (FPF_TARGET=0.0).
Processed C02101989: 9 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103507: 23 real entries (FPF_TARGET=0.0).
Processed C03104827: 21 real entries (FPF_TARGET=0.0).
Processed C01104541: 7 real entries (FPF_TARGET=0.0).
Processed C04102087: 20 real entries (FPF_TARGET=0.0).
Processed C03104683: 19 real entries (FPF_TARGET=0.0).
Processed C01101367: 13 real entries (FPF_TARGET=0.0).
Processed C01102994: 15 real entries (FPF_TARGET=0.0).
Processed C02100237: 23 real entries (FPF_TARGET=0.0).
Processed C01102175: 24 real entries (FPF_TARGET=0.0).
Processed C01100715: 16 real entries (FPF_TARGET=0.0).
Processed C03101844: 23 real entries (FPF_TARGET=0.0).
Processed C02104882: 16 real entries (FPF_TARGET=0.0).
Processed C04102866: 18 real entries (FPF_TARGET=0.0).
Processed C04101295: 24 real entries (FPF_TARGET=0.0).
Processed C01104551: 21 real entries (FPF_TARGET=0.0).
Processed C01102984: 19 real entries (FPF_TARGET=0.0).
Processed C01101377: 17 real entries (FPF_TARGET=0.0).
Processed C01103517: 15 real entries (FPF_TARGET=0.0).
Processed C02101883: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102097: 16 real entries (FPF_TARGET=0.0).
Processed C02104636: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101655: 19 real entries (FPF_TARGET=0.0).
Processed C01100705: 17 real entries (FPF_TARGET=0.0).
Processed C02101168: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102876: 20 real entries (FPF_TARGET=0.0).
Processed C02101010: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101854: 16 real entries (FPF_TARGET=0.0).
Processed C04101285: 20 real entries (FPF_TARGET=0.0).
Processed C01102165: 7 real entries (FPF_TARGET=0.0).
Processed C02102649: 13 real entries (FPF_TARGET=0.0).
Processed C02103602: 23 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100581: 24 real entries (FPF_TARGET=0.0).
Processed C01101001: 27 real entries (FPF_TARGET=0.0).
Processed C01104627: 9 real entries (FPF_TARGET=0.0).
Processed C02103343: 15 real entries (FPF_TARGET=0.0).
Processed C03102930: 24 real entries (FPF_TARGET=0.0).
Processed C02101523: 12 real entries (FPF_TARGET=0.0).
Processed C02102270: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101912: 20 real entries (FPF_TARGET=0.0).
Processed C01101998: 21 real entries (FPF_TARGET=0.0).
Processed C01101179: 18 real entries (FPF_TARGET=0.0).
Processed C01103661: 16 real entries (FPF_TARGET=0.0).
Processed C02102731: 20 real entries (FPF_TARGET=0.0).
Processed C04102299: 15 real entries (FPF_TARGET=0.0).
Processed C01100473: 17 real entries (FPF_TARGET=0.0).
Processed C02102202: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100151: 19 real entries (FPF_TARGET=0.0).
Processed C01102213: 24 real entries (FPF_TARGET=0.0).
Processed C03102848: 24 real entries (FPF_TARGET=0.0).
Processed C01103719: 15 real entries (FPF_TARGET=0.0).
Processed C04103793: 21 real entries (FPF_TARGET=0.0).
Processed C02103708: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101988: 8 real entries (FPF_TARGET=0.0).
Processed C02101533: 13 real entries (FPF_TARGET=0.0).
Processed C01101011: 13 real entries (FPF_TARGET=0.0).
Processed C01103671: 22 real entries (FPF_TARGET=0.0).
Processed C04101902: 22 real entries (FPF_TARGET=0.0).
Processed C02102659: 15 real entries (FPF_TARGET=0.0).
Processed C01104637: 21 real entries (FPF_TARGET=0.0).
Processed C04102289: 24 real entries (FPF_TARGET=0.0).
Processed C01102203: 27 real entries (FPF_TARGET=0.0).
Processed C01103709: 17 real entries (FPF_TARGET=0.0).
Processed C02100141: 15 real entries (FPF_TARGET=0.0).
Processed C02102721: 12 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C01103754: 14 real entries (FPF_TARGET=0.0).
Processed C03104912: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104096: 19 real entries (FPF_TARGET=0.0).
Processed C04100330: 20 real entries (FPF_TARGET=0.0).
Processed C01103949: 19 real entries (FPF_TARGET=0.0).
Processed C04104985: 15 real entries (FPF_TARGET=0.0).
Processed C02100698: 15 real entries (FPF_TARGET=0.0).
Processed C03104354: 23 real entries (FPF_TARGET=0.0).
Processed C02101392: 11 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C04102550: 23 real entries (FPF_TARGET=0.0).
Processed C03102618: 23 real entries (FPF_TARGET=0.0).
Processed C02103745: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104164: 22 real entries (FPF_TARGET=0.0).
Processed C04101742: 16 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C04103122: 21 real entries (FPF_TARGET=0.0).
Processed C03100100: 20 real entries (FPF_TARGET=0.0).
Processed C04102428: 15 real entries (FPF_TARGET=0.0).
Processed C03102760: 24 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C04104995: 20 real entries (FPF_TARGET=0.0).
Processed C02100688: 18 real entries (FPF_TARGET=0.0).
Processed C03102608: 22 real entries (FPF_TARGET=0.0).
Processed C03103302: 19 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C04100320: 17 real entries (FPF_TARGET=0.0).
Processed C03101562: 19 real entries (FPF_TARGET=0.0).
Processed C01103959: 18 real entries (FPF_TARGET=0.0).
Processed C01104086: 14 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C03104344: 18 real entries (FPF_TARGET=0.0).
Processed C03100068: 9 real entries (FPF_TARGET=0.0).
Processed C04103132: 18 real entries (FPF_TARGET=0.0).
Processed C03102770: 1 real entries (FPF_TARGET=0.0).
Processed C02102051: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102438: 18 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C02102809: 21 real entries (FPF_TARGET=0.0).
Processed C04104174: 20 real entries (FPF_TARGET=0.0).
Processed C03100889: 22 real entries (FPF_TARGET=0.0).
Processed C04100258: 20 real entries (FPF_TARGET=0.0).
Processed C03100110: 5 real entries (FPF_TARGET=0.0).
Processed C04101752: 16 real entries (FPF_TARGET=0.0).
Processed C03101327: 8 real entries (FPF_TARGET=0.0).
Processed C04100565: 22 real entries (FPF_TARGET=0.0).
Processed C04104649: 15 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C02104230: 7 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102305: 20 real entries (FPF_TARGET=0.0).
Processed C03104501: 20 real entries (FPF_TARGET=0.0).
Processed C04104731: 16 real entries (FPF_TARGET=0.0).
Processed C01100497: 8 real entries (FPF_TARGET=0.0).
Processed C04101117: 20 real entries (FPF_TARGET=0.0).
Processed C03104479: 8 real entries (FPF_TARGET=0.0).
Processed C03100755: 20 real entries (FPF_TARGET=0.0).
Processed C02104299: 18 real entries (FPF_TARGET=0.0).
Processed C02100621: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101804: 19 real entries (FPF_TARGET=0.0).
Processed C01103695: 24 real entries (FPF_TARGET=0.0).
Processed C03102135: 22 real entries (FPF_TARGET=0.0).
Processed C04102315: 16 real entries (FPF_TARGET=0.0).
Processed C04104659: 19 real entries (FPF_TARGET=0.0).
Processed C04100575: 24 real entries (FPF_TARGET=0.0).
Processed C03102125: 16 real entries (FPF_TARGET=0.0).
Processed C03104511: 23 real entries (FPF_TARGET=0.0).
Processed C04103767: 10 real entries (FPF_TARGET=0.0).
Processed C01100487: 9 real entries (FPF_TARGET=0.0).
Processed C04104721: 17 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03104469.parquet: No valid posted_date for consumer C03104469
Processed C02100631: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101107: 21 real entries (FPF_TARGET=0.0).
Processed C04102063: 10 real entries (FPF_TARGET=0.0).
Processed C03104667: 14 real entries (FPF_TARGET=0.0).
Processed C01101383: 25 real entries (FPF_TARGET=0.0).
Processed C02101253: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102970: 12 real entries (FPF_TARGET=0.0).
Processed C04100603: 17 real entries (FPF_TARGET=0.0).
Processed C01102191: 19 real entries (FPF_TARGET=0.0).Processed C02101406: 14 real entries and 20 simulations (FPF_TARGET=1.0).

Processed C01100689: 25 real entries (FPF_TARGET=0.0).
Processed C03103759: 20 real entries (FPF_TARGET=0.0).
Processed C04103411: 17 real entries (FPF_TARGET=0.0).
Processed C03102253: 18 real entries (FPF_TARGET=0.0).
Processed C04101271: 24 real entries (FPF_TARGET=0.0).
Processed C02101243: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104348: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102882: 21 real entries (FPF_TARGET=0.0).
Processed C01102808: 21 real entries (FPF_TARGET=0.0).
Processed C04101319: 23 real entries (FPF_TARGET=0.0).
Processed C02100074: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104457: 21 real entries (FPF_TARGET=0.0).
Processed C01101393: 14 real entries (FPF_TARGET=0.0).
Processed C03101139: 22 real entries (FPF_TARGET=0.0).
Processed C01102960: 16 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03101051.parquet: No valid features generated for consumer C03101051
Processed C01100699: 11 real entries (FPF_TARGET=0.0).
Processed C04100613: 23 real entries (FPF_TARGET=0.0).
Processed C04102073: 16 real entries (FPF_TARGET=0.0).
Processed C02100954: 8 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104677: 27 real entries (FPF_TARGET=0.0).
Processed C04103579: 25 real entries (FPF_TARGET=0.0).
Processed C04101261: 24 real entries (FPF_TARGET=0.0).
Processed C03103631: 16 real entries (FPF_TARGET=0.0).
Processed C04102892: 15 real entries (FPF_TARGET=0.0).
Processed C01102818: 16 real entries (FPF_TARGET=0.0).
Processed C03100423: 17 real entries (FPF_TARGET=0.0).
Processed C03101129: 7 real entries (FPF_TARGET=0.0).
Processed C02104876: 17 real entries (FPF_TARGET=0.0).
Processed C01102181: 18 real entries (FPF_TARGET=0.0).
Processed C03103749: 11 real entries (FPF_TARGET=0.0).
Processed C02102180: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102243: 12 real entries (FPF_TARGET=0.0).
Processed C02103830: 13 real entries (FPF_TARGET=0.0).
Processed C04102636: 20 real entries (FPF_TARGET=0.0).
Processed C02102971: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100945: 23 real entries (FPF_TARGET=0.0).
Processed C04100056: 21 real entries (FPF_TARGET=0.0).
Processed C03104032: 23 real entries (FPF_TARGET=0.0).
Processed C02101815: 12 real entries (FPF_TARGET=0.0).
Processed C04101424: 18 real entries (FPF_TARGET=0.0).
Processed C01104288: 16 real entries (FPF_TARGET=0.0).
Processed C03104022: 8 real entries (FPF_TARGET=0.0).
Processed C03101604: 19 real entries (FPF_TARGET=0.0).
Processed C03103895: 25 real entries (FPF_TARGET=0.0).
Processed C04100046: 22 real entries (FPF_TARGET=0.0).
Processed C03103064: 13 real entries (FPF_TARGET=0.0).
Processed C02102819: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102626: 23 real entries (FPF_TARGET=0.0).
Processed C01100955: 19 real entries (FPF_TARGET=0.0).
Processed C04101434: 20 real entries (FPF_TARGET=0.0).
Processed C01104298: 25 real entries (FPF_TARGET=0.0).
Processed C04104212: 11 real entries (FPF_TARGET=0.0).
Processed C02102961: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102416: 12 real entries (FPF_TARGET=0.0).
Processed C04103254: 22 real entries (FPF_TARGET=0.0).
Processed C03104050: 23 real entries (FPF_TARGET=0.0).
Processed C01104392: 22 real entries (FPF_TARGET=0.0).
Processed C04104318: 20 real entries (FPF_TARGET=0.0).
Processed C03101676: 21 real entries (FPF_TARGET=0.0).
Processed C03103016: 4 real entries (FPF_TARGET=0.0).
Processed C04102654: 17 real entries (FPF_TARGET=0.0).
Processed C02100944: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100927: 13 real entries (FPF_TARGET=0.0).
Processed C03104128: 8 real entries (FPF_TARGET=0.0).
Processed C02100486: 8 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104866: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100204: 14 real entries (FPF_TARGET=0.0).
Processed C04101446: 20 real entries (FPF_TARGET=0.0).
Processed C04104260: 22 real entries (FPF_TARGET=0.0).
Processed C03102464: 14 real entries (FPF_TARGET=0.0).
Processed C02101086: 19 real entries (FPF_TARGET=0.0).
Processed C04103226: 19 real entries (FPF_TARGET=0.0).
Processed C02103820: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104040: 18 real entries (FPF_TARGET=0.0).
Processed C02101805: 7 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103006: 19 real entries (FPF_TARGET=0.0).
Processed C04100024: 14 real entries (FPF_TARGET=0.0).
Processed C03102474: 16 real entries (FPF_TARGET=0.0).
Processed C04104308: 19 real entries (FPF_TARGET=0.0).
Processed C03100214: 15 real entries (FPF_TARGET=0.0).
Processed C04101456: 15 real entries (FPF_TARGET=0.0).
Processed C02102294: 16 real entries (FPF_TARGET=0.0).
Processed C04104270: 24 real entries (FPF_TARGET=0.0).
Processed C03104138: 22 real entries (FPF_TARGET=0.0).
Processed C04102998: 17 real entries (FPF_TARGET=0.0).
Processed C02104289: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102912: 21 real entries (FPF_TARGET=0.0).
Processed C03104605: 22 real entries (FPF_TARGET=0.0).
Processed C04100661: 23 real entries (FPF_TARGET=0.0).
Processed C04102001: 24 real entries (FPF_TARGET=0.0).
Processed C03100451: 16 real entries (FPF_TARGET=0.0).
Processed C03101023: 19 real entries (FPF_TARGET=0.0).
Processed C04100719: 13 real entries (FPF_TARGET=0.0).Processed C04104435: 17 real entries (FPF_TARGET=0.0).

Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102231.parquet: No valid posted_date for consumer C03102231
Processed C04102179: 20 real entries (FPF_TARGET=0.0).
Processed C02103948: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103473: 19 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03100539.parquet: No valid posted_date for consumer C03100539
Processed C04102011: 21 real entries (FPF_TARGET=0.0).
Processed C01103591: 24 real entries (FPF_TARGET=0.0).
Processed C04102169: 21 real entries (FPF_TARGET=0.0).
Processed C03104615: 19 real entries (FPF_TARGET=0.0).
Processed C03102359: 22 real entries (FPF_TARGET=0.0).
Processed C03102221: 14 real entries (FPF_TARGET=0.0).
Processed C03101033: 22 real entries (FPF_TARGET=0.0).
Processed C01101289: 19 real entries (FPF_TARGET=0.0).
Processed C04103463: 24 real entries (FPF_TARGET=0.0).
Processed C02104097: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104814: 18 real entries (FPF_TARGET=0.0).
Processed C01100783: 24 real entries (FPF_TARGET=0.0).
Processed C04104425: 24 real entries (FPF_TARGET=0.0).
Processed C03103525: 12 real entries (FPF_TARGET=0.0).
Processed C02103694: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101345: 1 real entries (FPF_TARGET=0.0).
Processed C04101994: 23 real entries (FPF_TARGET=0.0).
Processed C04100507: 18 real entries (FPF_TARGET=0.0).
Processed C04102367: 24 real entries (FPF_TARGET=0.0).
Processed C02100936: 15 real entries (FPF_TARGET=0.0).
Processed C04103715: 9 real entries (FPF_TARGET=0.0).
Processed C03102157: 8 real entries (FPF_TARGET=0.0).
Processed C02103958: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104753: 14 real entries (FPF_TARGET=0.0).
Processed C04100517: 11 real entries (FPF_TARGET=0.0).
Processed C03101355: 15 real entries (FPF_TARGET=0.0).
Processed C01101097: 21 real entries (FPF_TARGET=0.0).
Processed C03104573: 19 real entries (FPF_TARGET=0.0).
Processed C02104393: 13 real entries (FPF_TARGET=0.0).
Processed C03100727: 3 real entries (FPF_TARGET=0.0).
Processed C04104743: 18 real entries (FPF_TARGET=0.0).
Processed C03103535: 24 real entries (FPF_TARGET=0.0).
Processed C03102147: 20 real entries (FPF_TARGET=0.0).
Processed C04103705: 14 real entries (FPF_TARGET=0.0).
Processed C01101876: 19 real entries (FPF_TARGET=0.0).
Processed C04103038: 21 real entries (FPF_TARGET=0.0).
Processed C04102532: 19 real entries (FPF_TARGET=0.0).
Processed C03103370: 18 real entries (FPF_TARGET=0.0).
Processed C04100352: 4 real entries (FPF_TARGET=0.0).
Processed C03101510: 15 real entries (FPF_TARGET=0.0).
Processed C04101658: 25 real entries (FPF_TARGET=0.0).
Processed C03104336: 18 real entries (FPF_TARGET=0.0).
Processed C02103684: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103140: 20 real entries (FPF_TARGET=0.0).
Processed C03102702: 19 real entries (FPF_TARGET=0.0).
Processed C02101288: 19 real entries (FPF_TARGET=0.0).
Processed C03103208: 10 real entries (FPF_TARGET=0.0).
Processed C03101468: 19 real entries (FPF_TARGET=0.0).
Processed C02101096: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104106: 8 real entries (FPF_TARGET=0.0).
Processed C01103853: 23 real entries (FPF_TARGET=0.0).
Processed C04101720: 20 real entries (FPF_TARGET=0.0).
Processed C03100162: 20 real entries (FPF_TARGET=0.0).
Processed C04100342: 16 real entries (FPF_TARGET=0.0).
Processed C02100496: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104326: 17 real entries (FPF_TARGET=0.0).
Processed C04101648: 17 real entries (FPF_TARGET=0.0).
Processed C04103028: 18 real entries (FPF_TARGET=0.0).
Processed C02102913: 15 real entries (FPF_TARGET=0.0).
Processed C03100993: 9 real entries (FPF_TARGET=0.0).
Processed C03103360: 22 real entries (FPF_TARGET=0.0).
Processed C04104116: 18 real entries (FPF_TARGET=0.0).
Processed C03101478: 15 real entries (FPF_TARGET=0.0).
Processed C01104805: 23 real entries (FPF_TARGET=0.0).
Processed C02100792: 17 real entries (FPF_TARGET=0.0).
Processed C04103150: 9 real entries (FPF_TARGET=0.0).
Processed C03103218: 16 real entries (FPF_TARGET=0.0).
Processed C02101298: 15 real entries (FPF_TARGET=0.0).
Processed C02102676: 14 real entries (FPF_TARGET=0.0).
Processed C01100534: 13 real entries (FPF_TARGET=0.0).
Processed C01104618: 18 real entries (FPF_TARGET=0.0).
Processed C04104692: 19 real entries (FPF_TARGET=0.0).
Processed C01102354: 11 real entries (FPF_TARGET=0.0).
Processed C03102096: 19 real entries (FPF_TARGET=0.0).
Processed C02101867: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101146: 14 real entries (FPF_TARGET=0.0).
Processed C01104760: 14 real entries (FPF_TARGET=0.0).
Processed C04103401: 25 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102877: 23 real entries (FPF_TARGET=0.0).
Processed C02101877: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103726: 2 real entries (FPF_TARGET=0.0).
Processed C03101284: 30 real entries (FPF_TARGET=0.0).
Processed C02104242: 12 real entries (FPF_TARGET=0.0).
Processed C04103236: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102344: 21 real entries (FPF_TARGET=0.0).
Processed C01104608: 18 real entries (FPF_TARGET=0.0).
Processed C03102086: 14 real entries (FPF_TARGET=0.0).
Processed C02103852: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104682: 16 real entries (FPF_TARGET=0.0).
Processed C04101845: 13 real entries (FPF_TARGET=0.0).
Processed C01100524: 20 real entries (FPF_TARGET=0.0).
Processed C02104252: 13 real entries (FPF_TARGET=0.0).
Processed C02104383: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101156: 22 real entries (FPF_TARGET=0.0).
Processed C03101294: 11 real entries (FPF_TARGET=0.0).
Processed C03102867: 16 real entries (FPF_TARGET=0.0).
Processed C02102023: 17 real entries (FPF_TARGET=0.0).
Processed C04103918: 27 real entries (FPF_TARGET=0.0).
Processed C01103992: 23 real entries (FPF_TARGET=0.0).
Processed C01102501: 5 real entries (FPF_TARGET=0.0).
Processed C02101349: 17 real entries (FPF_TARGET=0.0).
Processed C02103590: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100782: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103081: 23 real entries (FPF_TARGET=0.0).
Processed C04101799: 23 real entries (FPF_TARGET=0.0).
Processed C04100293: 23 real entries (FPF_TARGET=0.0).
Processed C01100219: 23 real entries (FPF_TARGET=0.0).
Processed C04100709: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100842: 22 real entries (FPF_TARGET=0.0).
Processed C01102479: 9 real entries (FPF_TARGET=0.0).
Processed C02104417: 13 real entries (FPF_TARGET=0.0).
Processed C01103173: 13 real entries (FPF_TARGET=0.0).
Processed C03101500: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102511: 23 real entries (FPF_TARGET=0.0).
Processed C02100006: 7 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103982: 20 real entries (FPF_TARGET=0.0).
Processed C02100926: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103539: 17 real entries (FPF_TARGET=0.0).
Processed C01102469: 26 real entries (FPF_TARGET=0.0).
Processed C04104836: 17 real entries (FPF_TARGET=0.0).
Processed C03100852: 14 real entries (FPF_TARGET=0.0).
Processed C02103580: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101165: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103163: 13 real entries (FPF_TARGET=0.0).
Processed C04101789: 22 real entries (FPF_TARGET=0.0).
Processed C01101703: 20 real entries (FPF_TARGET=0.0).
Processed C04103870: 16 real entries (FPF_TARGET=0.0).
Processed C04100283: 18 real entries (FPF_TARGET=0.0).
Processed C01104125: 25 real entries (FPF_TARGET=0.0).
Processed C01100209: 23 real entries (FPF_TARGET=0.0).
Processed C02104609: 15 real entries (FPF_TARGET=0.0).
Processed C03104970: 12 real entries (FPF_TARGET=0.0).
Processed C01102667: 19 real entries (FPF_TARGET=0.0).
Processed C01100007: 9 real entries (FPF_TARGET=0.0).
Processed C02102345: 16 real entries (FPF_TARGET=0.0).
Processed C02101157: 12 real entries (FPF_TARGET=0.0).
Processed C03103936: 17 real entries (FPF_TARGET=0.0).
Processed C04102795: 13 real entries (FPF_TARGET=0.0).
Processed C02101474: 9 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101475: 22 real entries (FPF_TARGET=0.0).
Processed C01100017: 17 real entries (FPF_TARGET=0.0).
Processed C03104191: 19 real entries (FPF_TARGET=0.0).
Processed C03104808: 23 real entries (FPF_TARGET=0.0).
Processed C02102355: 17 real entries (FPF_TARGET=0.0).
Processed C04101597: 18 real entries (FPF_TARGET=0.0).
Processed C04100904: 18 real entries (FPF_TARGET=0.0).
Processed C03103926: 19 real entries (FPF_TARGET=0.0).
Processed C03104960: 23 real entries (FPF_TARGET=0.0).
Processed C01102677: 25 real entries (FPF_TARGET=0.0).
Processed C01104243: 19 real entries (FPF_TARGET=0.0).
Processed C02104761: 18 real entries (FPF_TARGET=0.0).
Processed C01101465: 23 real entries (FPF_TARGET=0.0).
Processed C04102785: 13 real entries (FPF_TARGET=0.0).
Processed C03104818: 18 real entries (FPF_TARGET=0.0).
Processed C01103538: 19 real entries (FPF_TARGET=0.0).
Processed C02101464: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103214: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102510: 16 real entries (FPF_TARGET=0.0).
Processed C01100652: 18 real entries (FPF_TARGET=0.0).
Processed C03100590: 16 real entries (FPF_TARGET=0.0).
Processed C01101358: 22 real entries (FPF_TARGET=0.0).
Processed C03102288: 11 real entries (FPF_TARGET=0.0).
Processed C03103782: 13 real entries (FPF_TARGET=0.0).
Processed C02100643: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101702: 16 real entries (FPF_TARGET=0.0).
Processed C01104406: 19 real entries (FPF_TARGET=0.0).
Processed C01101220: 22 real entries (FPF_TARGET=0.0).
Processed C02100016: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100642: 15 real entries (FPF_TARGET=0.0).
Processed C02102500: 12 real entries (FPF_TARGET=0.0).
Processed C02102033: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103528: 15 real entries (FPF_TARGET=0.0).
Processed C03101913: 8 real entries (FPF_TARGET=0.0).
Processed C01102022: 17 real entries (FPF_TARGET=0.0).
Processed C02103451: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104416: 23 real entries (FPF_TARGET=0.0).
Processed C04102849: 15 real entries (FPF_TARGET=0.0).
Processed C01101230: 22 real entries (FPF_TARGET=0.0).
Processed C01103450: 4 real entries (FPF_TARGET=0.0).
Processed C03102298: 7 real entries (FPF_TARGET=0.0).
Processed C02103529: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103792: 9 real entries (FPF_TARGET=0.0).
Processed C01100021: 20 real entries (FPF_TARGET=0.0).
Processed C02103669: 9 real entries (FPF_TARGET=0.0).
Processed C04104387: 22 real entries (FPF_TARGET=0.0).
Processed C02102363: 16 real entries (FPF_TARGET=0.0).
Processed C02103441: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100932: 24 real entries (FPF_TARGET=0.0).
Processed C02100535: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104956: 19 real entries (FPF_TARGET=0.0).
Processed C02101009: 20 real entries (FPF_TARGET=0.0).
Processed C01102641: 19 real entries (FPF_TARGET=0.0).
Processed C02103711: 19 real entries (FPF_TARGET=0.0).
Processed C03103089: 15 real entries (FPF_TARGET=0.0).
Processed C01104275: 23 real entries (FPF_TARGET=0.0).
Processed C03101791: 20 real entries (FPF_TARGET=0.0).
Processed C03103868: 18 real entries (FPF_TARGET=0.0).
Processed C01100159: 26 real entries (FPF_TARGET=0.0).
Processed C01101453: 21 real entries (FPF_TARGET=0.0).
Processed C02101231: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102739: 20 real entries (FPF_TARGET=0.0).
Processed C01102651: 9 real entries (FPF_TARGET=0.0).
Processed C02100513: 20 real entries (FPF_TARGET=0.0).
Processed C03102593: 14 real entries (FPF_TARGET=0.0).
Processed C02103679: 17 real entries (FPF_TARGET=0.0).
Processed C03103099: 19 real entries (FPF_TARGET=0.0).
Processed C02101359: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104397: 23 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C02100862: 15 real entries (FPF_TARGET=0.0).
Processed C04103511: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104437: 20 real entries (FPF_TARGET=0.0).
Processed C04101159: 17 real entries (FPF_TARGET=0.0).
Processed C03102003: 17 real entries (FPF_TARGET=0.0).
Processed C04103641: 17 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03103509.parquet: No valid posted_date for consumer C03103509
Processed C02104976: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101932: 15 real entries (FPF_TARGET=0.0).
Processed C02101589: 13 real entries (FPF_TARGET=0.0).
Processed C03100663: 13 real entries (FPF_TARGET=0.0).
Processed C02103848: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104607: 20 real entries (FPF_TARGET=0.0).
Processed C03101369: 23 real entries (FPF_TARGET=0.0).
Processed C04101021: 22 real entries (FPF_TARGET=0.0).
Processed C04100216: 26 real entries (FPF_TARGET=0.0).
Processed C03101454: 22 real entries (FPF_TARGET=0.0).
Processed C03104272: 22 real entries (FPF_TARGET=0.0).
Processed C01101796: 21 real entries (FPF_TARGET=0.0).
Processed C01104829: 11 real entries (FPF_TARGET=0.0).
Processed C04102476: 17 real entries (FPF_TARGET=0.0).Processed C03103234: 14 real entries (FPF_TARGET=0.0).

Processed C01103917: 17 real entries (FPF_TARGET=0.0).
Processed C03102013: 5 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100026: 24 real entries (FPF_TARGET=0.0).
Processed C04103004: 15 real entries (FPF_TARGET=0.0).
Processed C01102584: 24 real entries (FPF_TARGET=0.0).
Processed C01104839: 11 real entries (FPF_TARGET=0.0).
Processed C03102646: 21 real entries (FPF_TARGET=0.0).
Processed C04102466: 21 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03103224.parquet: No valid features generated for consumer C03103224
Processed C02103906: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100206: 18 real entries (FPF_TARGET=0.0).
Processed C03101444: 19 real entries (FPF_TARGET=0.0).
Processed C01101786: 20 real entries (FPF_TARGET=0.0).
Processed C03104262: 12 real entries (FPF_TARGET=0.0).
Processed C04103014: 19 real entries (FPF_TARGET=0.0).
Processed C01104941: 23 real entries (FPF_TARGET=0.0).
Processed C01102594: 23 real entries (FPF_TARGET=0.0).
Processed C04104052: 18 real entries (FPF_TARGET=0.0).
Processed C02101923: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100036: 15 real entries (FPF_TARGET=0.0).
Processed C04101674: 23 real entries (FPF_TARGET=0.0).
Processed C02101787: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101869: 27 real entries (FPF_TARGET=0.0).
Processed C02102732: 15 real entries (FPF_TARGET=0.0).
Processed C04103790: 20 real entries (FPF_TARGET=0.0).
Processed C01100470: 19 real entries (FPF_TARGET=0.0).
Processed C02101520: 12 real entries (FPF_TARGET=0.0).
Processed C04101911: 15 real entries (FPF_TARGET=0.0).
Processed C02104306: 16 real entries (FPF_TARGET=0.0).
Processed C01103662: 20 real entries (FPF_TARGET=0.0).
Processed C01101002: 15 real entries (FPF_TARGET=0.0).
Processed C04101088: 21 real entries (FPF_TARGET=0.0).
Processed C02101599: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100508: 16 real entries (FPF_TARGET=0.0).
Processed C01104624: 16 real entries (FPF_TARGET=0.0).
Processed C02100872: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102722: 18 real entries (FPF_TARGET=0.0).
Processed C01100460: 25 real entries (FPF_TARGET=0.0).
Processed C02101448: 16 real entries (FPF_TARGET=0.0).
Processed C01102200: 13 real entries (FPF_TARGET=0.0).
Processed C04101879: 19 real entries (FPF_TARGET=0.0).
Processed C01101012: 17 real entries (FPF_TARGET=0.0).
Processed C04101098: 18 real entries (FPF_TARGET=0.0).
Processed C02103350: 11 real entries (FPF_TARGET=0.0).
Processed C01100518: 22 real entries (FPF_TARGET=0.0).
Processed C03102923: 22 real entries (FPF_TARGET=0.0).
Processed C04100592: 22 real entries (FPF_TARGET=0.0).
Processed C01102378: 22 real entries (FPF_TARGET=0.0).
Processed C04101901: 21 real entries (FPF_TARGET=0.0).
Processed C03103142: 22 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103672: 10 real entries (FPF_TARGET=0.0).
Processed C02100093: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102445: 19 real entries (FPF_TARGET=0.0).
Processed C03102787: 5 real entries (FPF_TARGET=0.0).
Processed C01104890: 18 real entries (FPF_TARGET=0.0).
Processed C02102167: 13 real entries (FPF_TARGET=0.0).
Processed C04104183: 20 real entries (FPF_TARGET=0.0).
Processed C01104109: 12 real entries (FPF_TARGET=0.0).
Processed C03100906: 9 real entries (FPF_TARGET=0.0).
Processed C02102857: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100083: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104492: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104553: 18 real entries (FPF_TARGET=0.0).
Processed C04104962: 22 real entries (FPF_TARGET=0.0).
Processed C01101657: 20 real entries (FPF_TARGET=0.0).
Processed C04100443: 22 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104193: 24 real entries (FPF_TARGET=0.0).
Processed C01100235: 16 real entries (FPF_TARGET=0.0).
Processed C02102847: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102455: 17 real entries (FPF_TARGET=0.0).
Processed C03102797: 12 real entries (FPF_TARGET=0.0).
Processed C04103934: 11 real entries (FPF_TARGET=0.0).
Processed C02103238: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104061: 9 real entries (FPF_TARGET=0.0).
Processed C02103505: 19 real entries (FPF_TARGET=0.0).
Processed C03101585: 21 real entries (FPF_TARGET=0.0).
Processed C03100916: 21 real entries (FPF_TARGET=0.0).
Processed C04101664: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103027: 15 real entries (FPF_TARGET=0.0).
Processed C04104972: 21 real entries (FPF_TARGET=0.0).
Processed C01100143: 24 real entries (FPF_TARGET=0.0).
Processed C02104482: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102201: 12 real entries (FPF_TARGET=0.0).
Processed C03100281: 22 real entries (FPF_TARGET=0.0).
Processed C01103229: 20 real entries (FPF_TARGET=0.0).
Processed C04100850: 20 real entries (FPF_TARGET=0.0).
Processed C03104834: 23 real entries (FPF_TARGET=0.0).
Processed C01102723: 15 real entries (FPF_TARGET=0.0).
Processed C02103340: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102933: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101458: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104317: 18 real entries (FPF_TARGET=0.0).
Processed C03102599: 13 real entries (FPF_TARGET=0.0).
Processed C01101531: 20 real entries (FPF_TARGET=0.0).
Processed C01103351: 24 real entries (FPF_TARGET=0.0).
Processed C04100928: 21 real entries (FPF_TARGET=0.0).
Processed C02104316: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101375: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100471: 17 real entries (FPF_TARGET=0.0).
Processed C01103239: 13 real entries (FPF_TARGET=0.0).
Processed C01102733: 16 real entries (FPF_TARGET=0.0).
Processed C04100840: 20 real entries (FPF_TARGET=0.0).
Processed C02101530: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100153: 25 real entries (FPF_TARGET=0.0).
Processed C01101459: 22 real entries (FPF_TARGET=0.0).
Processed C03104824: 21 real entries (FPF_TARGET=0.0).
Processed C02102211: 16 real entries (FPF_TARGET=0.0).
Processed C03102589: 5 real entries (FPF_TARGET=0.0).
Processed C02104625: 16 real entries (FPF_TARGET=0.0).
Processed C03103862: 19 real entries (FPF_TARGET=0.0).
Processed C01103341: 11 real entries (FPF_TARGET=0.0).
Processed C02100509: 16 real entries (FPF_TARGET=0.0).
Processed C03103083: 9 real entries (FPF_TARGET=0.0).
Processed C02101003: 12 real entries (FPF_TARGET=0.0).
Processed C02103515: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100717: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103663: 15 real entries (FPF_TARGET=0.0).
Processed C01104307: 20 real entries (FPF_TARGET=0.0).
Processed C01101521: 10 real entries (FPF_TARGET=0.0).
Processed C01100716: 14 real entries (FPF_TARGET=0.0).
Processed C04101296: 16 real entries (FPF_TARGET=0.0).
Processed C04102865: 18 real entries (FPF_TARGET=0.0).
Processed C02102454: 15 real entries (FPF_TARGET=0.0).
Processed C02104118: 14 real entries (FPF_TARGET=0.0).
Processed C03101847: 15 real entries (FPF_TARGET=0.0).
Processed C01104542: 20 real entries (FPF_TARGET=0.0).
Processed C03104680: 4 real entries (FPF_TARGET=0.0).
Processed C01102176: 23 real entries (FPF_TARGET=0.0).
Processed C01102997: 14 real entries (FPF_TARGET=0.0).
Processed C01101364: 20 real entries (FPF_TARGET=0.0).
Processed C02102996: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103504: 21 real entries (FPF_TARGET=0.0).
Processed C02101646: 11 real entries (FPF_TARGET=0.0).
Processed C02102177: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100224: 14 real entries (FPF_TARGET=0.0).
Processed C03101857: 14 real entries (FPF_TARGET=0.0).
Processed C04102084: 23 real entries (FPF_TARGET=0.0).
Processed C01102166: 21 real entries (FPF_TARGET=0.0).
Processed C01100706: 21 real entries (FPF_TARGET=0.0).
Processed C04102875: 18 real entries (FPF_TARGET=0.0).
Processed C04101286: 22 real entries (FPF_TARGET=0.0).
Processed C01103514: 18 real entries (FPF_TARGET=0.0).
Processed C04102094: 26 real entries (FPF_TARGET=0.0).
Processed C01104552: 18 real entries (FPF_TARGET=0.0).
Processed C01102987: 23 real entries (FPF_TARGET=0.0).
Processed C01101374: 23 real entries (FPF_TARGET=0.0).
Processed C03104690: 14 real entries (FPF_TARGET=0.0).
Processed C02100256: 18 real entries (FPF_TARGET=0.0).
Processed C04103494: 18 real entries (FPF_TARGET=0.0).
Processed C02104543: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102114: 1 real entries (FPF_TARGET=0.0).
Processed C02102986: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100774: 20 real entries (FPF_TARGET=0.0).
Processed C01104458: 24 real entries (FPF_TARGET=0.0).
Processed C03101825: 15 real entries (FPF_TARGET=0.0).
Processed C01103566: 13 real entries (FPF_TARGET=0.0).
Processed C04102807: 9 real entries (FPF_TARGET=0.0).
Processed C02104002: 18 real entries (FPF_TARGET=0.0).
Processed C01100764: 25 real entries (FPF_TARGET=0.0).
Processed C04100686: 27 real entries (FPF_TARGET=0.0).
Processed C04102817: 9 real entries (FPF_TARGET=0.0).
Processed C04103484: 21 real entries (FPF_TARGET=0.0).
Processed C03101835: 16 real entries (FPF_TARGET=0.0).
Processed C02100461: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102104: 12 real entries (FPF_TARGET=0.0).
Processed C01104530: 18 real entries (FPF_TARGET=0.0).
Processed C02103054: 18 real entries (FPF_TARGET=0.0).
Processed C04100696: 18 real entries (FPF_TARGET=0.0).
Processed C02103673: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101316: 20 real entries (FPF_TARGET=0.0).
Processed C01103576: 20 real entries (FPF_TARGET=0.0).
Processed C03102483: 14 real entries (FPF_TARGET=0.0).
Processed C02104635: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100832: 20 real entries (FPF_TARGET=0.0).
Processed C03104856: 16 real entries (FPF_TARGET=0.0).
Processed C02100519: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103189: 18 real entries (FPF_TARGET=0.0).
Processed C01102741: 19 real entries (FPF_TARGET=0.0).
Processed C01100121: 19 real entries (FPF_TARGET=0.0).
Processed C02103769: 17 real entries (FPF_TARGET=0.0).
Processed C04104287: 19 real entries (FPF_TARGET=0.0).
Processed C02101656: 9 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103810: 15 real entries (FPF_TARGET=0.0).
Processed C02104060: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100234: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103333: 20 real entries (FPF_TARGET=0.0).
Processed C01102639: 21 real entries (FPF_TARGET=0.0).
Processed C01104375: 19 real entries (FPF_TARGET=0.0).
Processed C03103093: 22 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100059: 18 real entries (FPF_TARGET=0.0).
Processed C02102369: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101553: 10 real entries (FPF_TARGET=0.0).
Processed C03103968: 14 real entries (FPF_TARGET=0.0).
Processed C03101691: 24 real entries (FPF_TARGET=0.0).
Processed C04104297: 12 real entries (FPF_TARGET=0.0).
Processed C03103800: 16 real entries (FPF_TARGET=0.0).
Processed C02102426: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100413: 11 real entries (FPF_TARGET=0.0).
Processed C04100822: 19 real entries (FPF_TARGET=0.0).
Processed C03103199: 20 real entries (FPF_TARGET=0.0).
Processed C01102751: 22 real entries (FPF_TARGET=0.0).
Processed C03104846: 6 real entries (FPF_TARGET=0.0).
Processed C02101109: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101681: 16 real entries (FPF_TARGET=0.0).
Processed C01104365: 18 real entries (FPF_TARGET=0.0).
Processed C03103978: 24 real entries (FPF_TARGET=0.0).
Processed C01101543: 22 real entries (FPF_TARGET=0.0).
Processed C02101634: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101624: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103323: 22 real entries (FPF_TARGET=0.0).
Processed C01102629: 12 real entries (FPF_TARGET=0.0).
Processed C03100185: 18 real entries (FPF_TARGET=0.0).
Processed C01100247: 17 real entries (FPF_TARGET=0.0).
Processed C02103036: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100246: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104881: 23 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100765: 16 real entries (FPF_TARGET=0.0).
Processed C01102427: 22 real entries (FPF_TARGET=0.0).
Processed C04104099: 18 real entries (FPF_TARGET=0.0).
Processed C01101635: 21 real entries (FPF_TARGET=0.0).
Processed C01104013: 17 real entries (FPF_TARGET=0.0).
Processed C04103946: 21 real entries (FPF_TARGET=0.0).
Processed C03100964: 14 real entries (FPF_TARGET=0.0).
Processed C02101317: 16 real entries (FPF_TARGET=0.0).
Processed C03103397: 18 real entries (FPF_TARGET=0.0).
Processed C04104900: 21 real entries (FPF_TARGET=0.0).
Processed C02104531: 14 real entries (FPF_TARGET=0.0).
Processed C01102437: 19 real entries (FPF_TARGET=0.0).
Processed C03100195: 18 real entries (FPF_TARGET=0.0).
Processed C02104657: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100257: 25 real entries (FPF_TARGET=0.0).
Processed C02102263: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103611: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103387: 18 real entries (FPF_TARGET=0.0).
Processed C01103045: 24 real entries (FPF_TARGET=0.0).
Processed C04104910: 20 real entries (FPF_TARGET=0.0).
Processed C01101625: 22 real entries (FPF_TARGET=0.0).
Processed C04104089: 19 real entries (FPF_TARGET=0.0).
Processed C01101118: 22 real entries (FPF_TARGET=0.0).
Processed C03102829: 19 real entries (FPF_TARGET=0.0).
Processed C04100498: 18 real entries (FPF_TARGET=0.0).
Processed C01102272: 17 real entries (FPF_TARGET=0.0).
Processed C01101881: 15 real entries (FPF_TARGET=0.0).
Processed C01103778: 13 real entries (FPF_TARGET=0.0).
Processed C02101071: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101060: 22 real entries (FPF_TARGET=0.0).
Processed C02101890: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102951: 12 real entries (FPF_TARGET=0.0).
Processed C02103322: 12 real entries (FPF_TARGET=0.0).
Processed C01104646: 13 real entries (FPF_TARGET=0.0).
Processed C02101542: 16 real entries (FPF_TARGET=0.0).
Processed C02103779: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101973: 19 real entries (FPF_TARGET=0.0).
Processed C02100048: 14 real entries (FPF_TARGET=0.0).
Processed C02101119: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102262: 24 real entries (FPF_TARGET=0.0).
Processed C01101891: 17 real entries (FPF_TARGET=0.0).
Processed C01103768: 15 real entries (FPF_TARGET=0.0).
Processed C02102273: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101108: 14 real entries (FPF_TARGET=0.0).
Processed C03102839: 22 real entries (FPF_TARGET=0.0).
Processed C04100488: 16 real entries (FPF_TARGET=0.0).
Processed C04101963: 24 real entries (FPF_TARGET=0.0).
Processed C02101552: 12 real entries (FPF_TARGET=0.0).
Processed C01103610: 17 real entries (FPF_TARGET=0.0).
Processed C01101070: 19 real entries (FPF_TARGET=0.0).
Processed C03104594: 6 real entries (FPF_TARGET=0.0).
Processed C02102638: 16 real entries (FPF_TARGET=0.0).
Processed C01104656: 2 real entries (FPF_TARGET=0.0).
Processed C03102941: 7 real entries (FPF_TARGET=0.0).
Processed C01103194: 20 real entries (FPF_TARGET=0.0).
Processed C02104647: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102414: 20 real entries (FPF_TARGET=0.0).
Processed C03103256: 18 real entries (FPF_TARGET=0.0).
Processed C04100274: 21 real entries (FPF_TARGET=0.0).
Processed C02102105: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101436: 21 real entries (FPF_TARGET=0.0).
Processed C04104158: 20 real entries (FPF_TARGET=0.0).
Processed C02103577: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104210: 13 real entries (FPF_TARGET=0.0).
Processed C04103066: 20 real entries (FPF_TARGET=0.0).
Processed C04104020: 23 real entries (FPF_TARGET=0.0).
Processed C03102624: 23 real entries (FPF_TARGET=0.0).
Processed C01100386: 20 real entries (FPF_TARGET=0.0).
Processed C01103975: 21 real entries (FPF_TARGET=0.0).
Processed C03100044: 11 real entries (FPF_TARGET=0.0).
Processed C04101606: 25 real entries (FPF_TARGET=0.0).
Processed C02104521: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104148: 16 real entries (FPF_TARGET=0.0).
Processed C02100775: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104368: 23 real entries (FPF_TARGET=0.0).
Processed C03104200: 17 real entries (FPF_TARGET=0.0).
Processed C04100264: 27 real entries (FPF_TARGET=0.0).
Processed C01103184: 10 real entries (FPF_TARGET=0.0).
Processed C02102115: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103965: 17 real entries (FPF_TARGET=0.0).
Processed C04102404: 21 real entries (FPF_TARGET=0.0).
Processed C01100396: 21 real entries (FPF_TARGET=0.0).
Processed C03104378: 1 real entries (FPF_TARGET=0.0).
Processed C03103246: 18 real entries (FPF_TARGET=0.0).
Processed C02104459: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104030: 23 real entries (FPF_TARGET=0.0).
Processed C01104923: 7 real entries (FPF_TARGET=0.0).
Processed C04103076: 16 real entries (FPF_TARGET=0.0).
Processed C04101616: 23 real entries (FPF_TARGET=0.0).
Processed C01101838: 25 real entries (FPF_TARGET=0.0).
Processed C04102241: 16 real entries (FPF_TARGET=0.0).
Processed C02101483: 18 real entries (FPF_TARGET=0.0).
Processed C03102109: 23 real entries (FPF_TARGET=0.0).
Processed C03103403: 19 real entries (FPF_TARGET=0.0).
Processed C02101307: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104787: 21 real entries (FPF_TARGET=0.0).
Processed C03102890: 18 real entries (FPF_TARGET=0.0).
Processed C04100421: 13 real entries (FPF_TARGET=0.0).
Processed C03101263: 19 real entries (FPF_TARGET=0.0).
Processed C04103633: 18 real entries (FPF_TARGET=0.0).
Processed C03100769: 17 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C04102364: 22 real entries (FPF_TARGET=0.0).
Processed C01101875: 12 real entries (FPF_TARGET=0.0).
Processed C03102144: 16 real entries (FPF_TARGET=0.0).
Processed C04104740: 17 real entries (FPF_TARGET=0.0).
Processed C02104241: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100724: 21 real entries (FPF_TARGET=0.0).
Processed C02104390: 12 real entries (FPF_TARGET=0.0).
Processed C03104408: 21 real entries (FPF_TARGET=0.0).
Processed C04101987: 21 real entries (FPF_TARGET=0.0).
Processed C04100514: 22 real entries (FPF_TARGET=0.0).
Processed C03103536: 21 real entries (FPF_TARGET=0.0).
Processed C03104570: 10 real entries (FPF_TARGET=0.0).
Processed C01101094: 21 real entries (FPF_TARGET=0.0).
Processed C04100229: 25 real entries (FPF_TARGET=0.0).
Processed C04104105: 22 real entries (FPF_TARGET=0.0).
Processed C02104414: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101723: 15 real entries (FPF_TARGET=0.0).
Processed C03100161: 17 real entries (FPF_TARGET=0.0).
Processed C04103143: 22 real entries (FPF_TARGET=0.0).
Processed C01102031: 23 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104816: 22 real entries (FPF_TARGET=0.0).
Processed C03102701: 15 real entries (FPF_TARGET=0.0).
Processed C02101232: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103928: 17 real entries (FPF_TARGET=0.0).
Processed C03100019: 18 real entries (FPF_TARGET=0.0).
Processed C03101513: 23 real entries (FPF_TARGET=0.0).
Processed C04100351: 23 real entries (FPF_TARGET=0.0).
Processed C02100640: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100980: 5 real entries (FPF_TARGET=0.0).
Processed C02100728: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102531: 19 real entries (FPF_TARGET=0.0).
Processed C02102900: 19 real entries (FPF_TARGET=0.0).
Processed C01104806: 12 real entries (FPF_TARGET=0.0).
Processed C03102679: 24 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102711.parquet: No valid posted_date for consumer C03102711
Processed C03103373: 23 real entries (FPF_TARGET=0.0).
Processed C04103153: 9 real entries (FPF_TARGET=0.0).
Processed C02102868: 16 real entries (FPF_TARGET=0.0).
Processed C04102459: 22 real entries (FPF_TARGET=0.0).
Processed C01103840: 22 real entries (FPF_TARGET=0.0).
Processed C04104115: 25 real entries (FPF_TARGET=0.0).
Processed C04100239: 19 real entries (FPF_TARGET=0.0).
Processed C04101733: 22 real entries (FPF_TARGET=0.0).
Processed C03100171: 20 real entries (FPF_TARGET=0.0).
Processed C03101503: 12 real entries (FPF_TARGET=0.0).
Processed C03100990: 19 real entries (FPF_TARGET=0.0).
Processed C01103938: 15 real entries (FPF_TARGET=0.0).
Processed C04100341: 25 real entries (FPF_TARGET=0.0).
Processed C02102020: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104325: 7 real entries (FPF_TARGET=0.0).
Processed C02102089: 13 real entries (FPF_TARGET=0.0).
Processed C04103225: 17 real entries (FPF_TARGET=0.0).
Processed C03100009: 16 real entries (FPF_TARGET=0.0).
Processed C02102287: 15 real entries (FPF_TARGET=0.0).
Processed C03102467: 21 real entries (FPF_TARGET=0.0).
Processed C04101445: 22 real entries (FPF_TARGET=0.0).
Processed C02104404: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101222: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102657: 10 real entries (FPF_TARGET=0.0).
Processed C04104263: 24 real entries (FPF_TARGET=0.0).
Processed C02101095: 14 real entries (FPF_TARGET=0.0).
Processed C01100924: 22 real entries (FPF_TARGET=0.0).
Processed C01104391: 14 real entries (FPF_TARGET=0.0).
Processed C03104053: 11 real entries (FPF_TARGET=0.0).
Processed C04101455: 21 real entries (FPF_TARGET=0.0).
Processed C03100217: 20 real entries (FPF_TARGET=0.0).
Processed C03101675: 26 real entries (FPF_TARGET=0.0).
Processed C02101864: 12 real entries (FPF_TARGET=0.0).
Processed C04104273: 17 real entries (FPF_TARGET=0.0).
Processed C04103235: 18 real entries (FPF_TARGET=0.0).Processed C03104043: 9 real entries (FPF_TARGET=0.0).

Processed C01104381: 23 real entries (FPF_TARGET=0.0).
Processed C02101085: 12 real entries (FPF_TARGET=0.0).
Processed C04102647: 25 real entries (FPF_TARGET=0.0).
Processed C04101846: 23 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103005: 21 real entries (FPF_TARGET=0.0).
Processed C01100934: 20 real entries (FPF_TARGET=0.0).
Processed C03103738: 19 real entries (FPF_TARGET=0.0).
Processed C03102232: 23 real entries (FPF_TARGET=0.0).
Processed C04103470: 20 real entries (FPF_TARGET=0.0).
Processed C01102869: 22 real entries (FPF_TARGET=0.0).
Processed C03100452: 18 real entries (FPF_TARGET=0.0).
Processed C04101210: 15 real entries (FPF_TARGET=0.0).
Processed C04104436: 18 real entries (FPF_TARGET=0.0).
Processed C02104807: 12 real entries (FPF_TARGET=0.0).
Processed C01100790: 18 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03101158.parquet: No valid features generated for consumer C03101158
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03103640.parquet: No valid posted_date for consumer C03103640
Processed C01102088: 17 real entries (FPF_TARGET=0.0).
Processed C04102002: 26 real entries (FPF_TARGET=0.0).
Processed C01103582: 21 real entries (FPF_TARGET=0.0).
Processed C04103508: 16 real entries (FPF_TARGET=0.0).
Processed C02100925: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104606: 18 real entries (FPF_TARGET=0.0).
Processed C01102911: 13 real entries (FPF_TARGET=0.0).
Processed C04101368: 19 real entries (FPF_TARGET=0.0).
Processed C03101020: 20 real entries (FPF_TARGET=0.0).
Processed C04100662: 17 real entries (FPF_TARGET=0.0).
Processed C03100442: 20 real entries (FPF_TARGET=0.0).
Processed C01102879: 28 real entries (FPF_TARGET=0.0).
Processed C02100935: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100780: 15 real entries (FPF_TARGET=0.0).
Processed C03101148: 13 real entries (FPF_TARGET=0.0).
Processed C02104817: 16 real entries (FPF_TARGET=0.0).
Processed C03100207: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104426: 20 real entries (FPF_TARGET=0.0).
Processed C03103728: 19 real entries (FPF_TARGET=0.0).
Processed C03102222: 15 real entries (FPF_TARGET=0.0).
Processed C02103851: 14 real entries (FPF_TARGET=0.0).
Processed C01102901: 8 real entries (FPF_TARGET=0.0).
Processed C03104616: 18 real entries (FPF_TARGET=0.0).
Processed C03101030: 19 real entries (FPF_TARGET=0.0).
Processed C02100791: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102098: 3 real entries (FPF_TARGET=0.0).
Processed C03103650: 19 real entries (FPF_TARGET=0.0).
Processed C04102012: 21 real entries (FPF_TARGET=0.0).
Processed C04103518: 10 real entries (FPF_TARGET=0.0).
Processed C02102910: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101272: 27 real entries (FPF_TARGET=0.0).
Processed C04102881: 9 real entries (FPF_TARGET=0.0).
Processed C02103593: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102878: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104454: 23 real entries (FPF_TARGET=0.0).
Processed C04100778: 28 real entries (FPF_TARGET=0.0).
Processed C01102192: 22 real entries (FPF_TARGET=0.0).
Processed C02103823: 17 real entries (FPF_TARGET=0.0).
Processed C04102118: 19 real entries (FPF_TARGET=0.0).
Processed C03102250: 25 real entries (FPF_TARGET=0.0).
Processed C01103498: 19 real entries (FPF_TARGET=0.0).
Processed C03104664: 18 real entries (FPF_TARGET=0.0).
Processed C01101380: 15 real entries (FPF_TARGET=0.0).
Processed C01102973: 25 real entries (FPF_TARGET=0.0).
Processed C04100600: 20 real entries (FPF_TARGET=0.0).
Processed C03100548: 23 real entries (FPF_TARGET=0.0).
Processed C02103583: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102328: 18 real entries (FPF_TARGET=0.0).
Processed C04102060: 23 real entries (FPF_TARGET=0.0).
Processed C01102182: 20 real entries (FPF_TARGET=0.0).
Processed C03102240: 17 real entries (FPF_TARGET=0.0).
Processed C04102108: 22 real entries (FPF_TARGET=0.0).
Processed C04103402: 24 real entries (FPF_TARGET=0.0).
Processed C04102891: 18 real entries (FPF_TARGET=0.0).
Processed C02103833: 16 real entries (FPF_TARGET=0.0).
Processed C02104875: 15 real entries (FPF_TARGET=0.0).
Processed C04100768: 24 real entries (FPF_TARGET=0.0).
Processed C04104444: 23 real entries (FPF_TARGET=0.0).
Processed C02103841: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103632: 10 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C01101390.parquet: No valid features generated for consumer C01101390
Processed C04102070: 23 real entries (FPF_TARGET=0.0).
Processed C03100558: 8 real entries (FPF_TARGET=0.0).
Processed C01102963: 20 real entries (FPF_TARGET=0.0).
Processed C03101052: 10 real entries (FPF_TARGET=0.0).
Processed C04101166: 24 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101816: 18 real entries (FPF_TARGET=0.0).
Processed C04100610: 23 real entries (FPF_TARGET=0.0).
Processed C04101427: 21 real entries (FPF_TARGET=0.0).
Processed C03104674: 25 real entries (FPF_TARGET=0.0).
Processed C04100037: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104201: 21 real entries (FPF_TARGET=0.0).
Processed C03100265: 19 real entries (FPF_TARGET=0.0).
Processed C04103247: 17 real entries (FPF_TARGET=0.0).
Processed C04104379: 19 real entries (FPF_TARGET=0.0).
Processed C02103697: 16 real entries (FPF_TARGET=0.0).
Processed C03104031: 24 real entries (FPF_TARGET=0.0).
Processed C03102669: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101665: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103077: 17 real entries (FPF_TARGET=0.0).
Processed C04100055: 21 real entries (FPF_TARGET=0.0).
Processed C04103257: 19 real entries (FPF_TARGET=0.0).
Processed C04102635: 19 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03100275.parquet: No valid features generated for consumer C03100275
Processed C03103886: 3 real entries (FPF_TARGET=0.0).
Processed C03102415: 22 real entries (FPF_TARGET=0.0).
Processed C04101437: 21 real entries (FPF_TARGET=0.0).
Processed C02101806: 17 real entries (FPF_TARGET=0.0).
Processed C04104211: 14 real entries (FPF_TARGET=0.0).
Processed C02103939: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102625: 20 real entries (FPF_TARGET=0.0).
Processed C01100956: 20 real entries (FPF_TARGET=0.0).
Processed C03104159: 23 real entries (FPF_TARGET=0.0).
Processed C04100045: 14 real entries (FPF_TARGET=0.0).
Processed C01104874: 18 real entries (FPF_TARGET=0.0).
Processed C03100430: 9 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101409: 10 real entries (FPF_TARGET=0.0).
Processed C03102763: 18 real entries (FPF_TARGET=0.0).
Processed C03101607: 25 real entries (FPF_TARGET=0.0).
Processed C04104167: 22 real entries (FPF_TARGET=0.0).
Processed C01103832: 23 real entries (FPF_TARGET=0.0).
Processed C04103059: 14 real entries (FPF_TARGET=0.0).
Processed C03103269: 20 real entries (FPF_TARGET=0.0).
Processed C04104986: 20 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03103311.parquet: No valid posted_date for consumer C03103311
Processed C04102553: 15 real entries (FPF_TARGET=0.0).
Processed C02101391: 11 real entries (FPF_TARGET=0.0).
Processed C01104095: 13 real entries (FPF_TARGET=0.0).
Processed C04100333: 20 real entries (FPF_TARGET=0.0).
Processed C04101639: 18 real entries (FPF_TARGET=0.0).
Processed C03101571: 22 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03104357.parquet: No valid features generated for consumer C03104357
Processed C04104177: 22 real entries (FPF_TARGET=0.0).
Processed C01103822: 20 real entries (FPF_TARGET=0.0).
Processed C03101419: 26 real entries (FPF_TARGET=0.0).
Processed C03100113: 15 real entries (FPF_TARGET=0.0).
Processed C04101751: 13 real entries (FPF_TARGET=0.0).
Processed C03102773: 20 real entries (FPF_TARGET=0.0).
Processed C04103131: 20 real entries (FPF_TARGET=0.0).
Processed C03103279: 11 real entries (FPF_TARGET=0.0).
Processed C03101561: 14 real entries (FPF_TARGET=0.0).
Processed C01104085: 17 real entries (FPF_TARGET=0.0).
Processed C03104347: 20 real entries (FPF_TARGET=0.0).
Processed C04104996: 19 real entries (FPF_TARGET=0.0).
Processed C02102972: 13 real entries (FPF_TARGET=0.0).
Processed C03103301: 21 real entries (FPF_TARGET=0.0).
Processed C04102543: 17 real entries (FPF_TARGET=0.0).
Processed C03102136: 21 real entries (FPF_TARGET=0.0).
Processed C01101807: 19 real entries (FPF_TARGET=0.0).
Processed C04104732: 15 real entries (FPF_TARGET=0.0).
Processed C01100494: 5 real entries (FPF_TARGET=0.0).
Processed C02104865: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101114: 16 real entries (FPF_TARGET=0.0).
Processed C03104021: 7 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100756: 1 real entries (FPF_TARGET=0.0).
Processed C04102306: 14 real entries (FPF_TARGET=0.0).
Processed C01103686: 12 real entries (FPF_TARGET=0.0).
Processed C03104502: 18 real entries (FPF_TARGET=0.0).
Processed C01100484: 16 real entries (FPF_TARGET=0.0).
Processed C03100746: 9 real entries (FPF_TARGET=0.0).
Processed C04101104: 24 real entries (FPF_TARGET=0.0).
Processed C01101817: 23 real entries (FPF_TARGET=0.0).
Processed C04101200: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102126: 19 real entries (FPF_TARGET=0.0).
Processed C02100947: 14 real entries (FPF_TARGET=0.0).
Processed C03101334: 20 real entries (FPF_TARGET=0.0).
Processed C01103696: 17 real entries (FPF_TARGET=0.0).
Processed C02104094: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104512: 17 real entries (FPF_TARGET=0.0).
Processed C04102316: 22 real entries (FPF_TARGET=0.0).
Processed C01101772: 10 real entries (FPF_TARGET=0.0).
Processed C04103801: 18 real entries (FPF_TARGET=0.0).
Processed C01100278: 23 real entries (FPF_TARGET=0.0).
Processed C02103430: 15 real entries (FPF_TARGET=0.0).
Processed C03104296: 18 real entries (FPF_TARGET=0.0).
Processed C03103554: 23 real entries (FPF_TARGET=0.0).
Processed C03100823: 2 real entries (FPF_TARGET=0.0).
Processed C02101250: 18 real entries (FPF_TARGET=0.0).
Processed C01104154: 25 real entries (FPF_TARGET=0.0).
Processed C02104476: 15 real entries (FPF_TARGET=0.0).
Processed C04102492: 21 real entries (FPF_TARGET=0.0).
Processed C01102418: 23 real entries (FPF_TARGET=0.0).
Processed C04103198: 23 real entries (FPF_TARGET=0.0).
Processed C02103929: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100300: 18 real entries (FPF_TARGET=0.0).
Processed C04104847: 21 real entries (FPF_TARGET=0.0).
Processed C04103979: 18 real entries (FPF_TARGET=0.0).
Processed C01102560: 18 real entries (FPF_TARGET=0.0).
Processed C01102408: 19 real entries (FPF_TARGET=0.0).
Processed C04102482: 21 real entries (FPF_TARGET=0.0).
Processed C02103499: 9 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104857: 22 real entries (FPF_TARGET=0.0).
Processed C04101741: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103102: 18 real entries (FPF_TARGET=0.0).
Processed C01101762: 12 real entries (FPF_TARGET=0.0).
Processed C03104286: 14 real entries (FPF_TARGET=0.0).
Processed C01104144: 26 real entries (FPF_TARGET=0.0).
Processed C03101617: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103420: 20 real entries (FPF_TARGET=0.0).
Processed C04103811: 21 real entries (FPF_TARGET=0.0).
Processed C01100268: 23 real entries (FPF_TARGET=0.0).
Processed C02103687: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103067: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101378: 23 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102570: 18 real entries (FPF_TARGET=0.0).
Processed C02102052: 15 real entries (FPF_TARGET=0.0).
Processed C04103969: 16 real entries (FPF_TARGET=0.0).
Processed C01101127: 16 real entries (FPF_TARGET=0.0).
Processed C04101690: 24 real entries (FPF_TARGET=0.0).
Processed C03103485: 15 real entries (FPF_TARGET=0.0).
Processed C02101405: 15 real entries (FPF_TARGET=0.0).
Processed C02104223: 14 real entries (FPF_TARGET=0.0).
Processed C03102816: 23 real entries (FPF_TARGET=0.0).
Processed C01103747: 21 real entries (FPF_TARGET=0.0).
Processed C03100420: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100697: 21 real entries (FPF_TARGET=0.0).
Processed C01104679: 19 real entries (FPF_TARGET=0.0).
Processed C01100555: 19 real entries (FPF_TARGET=0.0).
Processed C01102335: 23 real entries (FPF_TARGET=0.0).
Processed C02100077: 22 real entries (FPF_TARGET=0.0).
Processed C02101415: 13 real entries (FPF_TARGET=0.0).
Processed C03103495: 8 real entries (FPF_TARGET=0.0).
Processed C04101824: 17 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102806.parquet: No valid posted_date for consumer C03102806
Processed C01101137: 22 real entries (FPF_TARGET=0.0).
Processed C02102962: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100886: 17 real entries (FPF_TARGET=0.0).
Processed C02103275: 11 real entries (FPF_TARGET=0.0).
Processed C02100067: 14 real entries (FPF_TARGET=0.0).
Processed C01102325: 20 real entries (FPF_TARGET=0.0).
Processed C03100687: 19 real entries (FPF_TARGET=0.0).
Processed C02102607: 20 real entries (FPF_TARGET=0.0).
Processed C01104669: 13 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C01100545.parquet: No valid features generated for consumer C01100545
Processed C02100269: 18 real entries (FPF_TARGET=0.0).
Processed C02104145: 14 real entries (FPF_TARGET=0.0).
Processed C01103421: 24 real entries (FPF_TARGET=0.0).
Processed C01104467: 21 real entries (FPF_TARGET=0.0).
Processed C02103103: 15 real entries (FPF_TARGET=0.0).
Processed C03101183: 19 real entries (FPF_TARGET=0.0).
Processed C03102391: 10 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03101962.parquet: No valid features generated for consumer C03101962
Processed C01103559: 22 real entries (FPF_TARGET=0.0).
Processed C02100311: 16 real entries (FPF_TARGET=0.0).
Processed C01102053: 8 real entries (FPF_TARGET=0.0).
Processed C04104595: 21 real entries (FPF_TARGET=0.0).
Processed C01101339: 12 real entries (FPF_TARGET=0.0).
Processed C04102940: 22 real entries (FPF_TARGET=0.0).
Processed C03101193: 17 real entries (FPF_TARGET=0.0).
Processed C02104466: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104477: 16 real entries (FPF_TARGET=0.0).
Processed C02100957: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101251: 22 real entries (FPF_TARGET=0.0).
Processed C03100499: 14 real entries (FPF_TARGET=0.0).
Processed C04102828: 19 real entries (FPF_TARGET=0.0).
Processed C01103431: 16 real entries (FPF_TARGET=0.0).
Processed C02103548: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100279: 18 real entries (FPF_TARGET=0.0).
Processed C02104233: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103265: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104585: 11 real entries (FPF_TARGET=0.0).
Processed C02100622: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100623: 21 real entries (FPF_TARGET=0.0).
Processed C01101329: 22 real entries (FPF_TARGET=0.0).
Processed C04102950: 20 real entries (FPF_TARGET=0.0).
Processed C02100301: 17 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C01104241: 21 real entries (FPF_TARGET=0.0).
Processed C02101094: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101710: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101585: 22 real entries (FPF_TARGET=0.0).
Processed C01100005: 23 real entries (FPF_TARGET=0.0).
Processed C03104972: 19 real entries (FPF_TARGET=0.0).
Processed C01102665: 20 real entries (FPF_TARGET=0.0).
Processed C04100916: 12 real entries (FPF_TARGET=0.0).
Processed C02101668: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104193: 13 real entries (FPF_TARGET=0.0).
Processed C02103008: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104251: 21 real entries (FPF_TARGET=0.0).
Processed C04102797: 18 real entries (FPF_TARGET=0.0).
Processed C04100663: 22 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103991: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103217: 23 real entries (FPF_TARGET=0.0).
Processed C01100373: 16 real entries (FPF_TARGET=0.0).
Processed C02102512: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103980: 18 real entries (FPF_TARGET=0.0).
Processed C01101679: 12 real entries (FPF_TARGET=0.0).
Processed C02102031: 13 real entries (FPF_TARGET=0.0).
Processed C04103093: 17 real entries (FPF_TARGET=0.0).
Processed C01103019: 23 real entries (FPF_TARGET=0.0).
Processed C02104136: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102599: 20 real entries (FPF_TARGET=0.0).
Processed C03100928: 14 real entries (FPF_TARGET=0.0).
Processed C01102513: 21 real entries (FPF_TARGET=0.0).
Processed C01104127: 9 real entries (FPF_TARGET=0.0).
Processed C02103443: 13 real entries (FPF_TARGET=0.0).
Processed C02104126: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101701: 23 real entries (FPF_TARGET=0.0).
Processed C03100592: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103161: 22 real entries (FPF_TARGET=0.0).
Processed C04104834: 22 real entries (FPF_TARGET=0.0).
Processed C02100729: 16 real entries (FPF_TARGET=0.0).
Processed C02101223: 20 real entries (FPF_TARGET=0.0).
Processed C03100850: 26 real entries (FPF_TARGET=0.0).
Processed C04103083: 19 real entries (FPF_TARGET=0.0).
Processed C02100372: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102589: 12 real entries (FPF_TARGET=0.0).
Processed C01102503: 20 real entries (FPF_TARGET=0.0).
Processed C01103990: 23 real entries (FPF_TARGET=0.0).
Processed C02100527: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102021: 17 real entries (FPF_TARGET=0.0).
Processed C02103735: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100739: 14 real entries (FPF_TARGET=0.0).
Processed C04104824: 22 real entries (FPF_TARGET=0.0).
Processed C02104415: 17 real entries (FPF_TARGET=0.0).
Processed C01103171: 21 real entries (FPF_TARGET=0.0).
Processed C03100840: 21 real entries (FPF_TARGET=0.0).
Processed C04103862: 24 real entries (FPF_TARGET=0.0).
Processed C02102159: 21 real entries (FPF_TARGET=0.0).
Processed C01100526: 17 real entries (FPF_TARGET=0.0).
Processed C02102357: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104680: 22 real entries (FPF_TARGET=0.0).
Processed C03102084: 19 real entries (FPF_TARGET=0.0).
Processed C02100651: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101155: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103725: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104773: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103216: 12 real entries (FPF_TARGET=0.0).
Processed C01102346: 26 real entries (FPF_TARGET=0.0).
Processed C03102865: 9 real entries (FPF_TARGET=0.0).
Processed C01104772: 23 real entries (FPF_TARGET=0.0).
Processed C01103734: 9 real entries (FPF_TARGET=0.0).
Processed C04101847: 13 real entries (FPF_TARGET=0.0).
Processed C03103934: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101296: 23 real entries (FPF_TARGET=0.0).
Processed C01101154: 27 real entries (FPF_TARGET=0.0).
Processed C02100014: 12 real entries (FPF_TARGET=0.0).
Processed C03102094: 15 real entries (FPF_TARGET=0.0).
Processed C01102356: 13 real entries (FPF_TARGET=0.0).
Processed C04104690: 19 real entries (FPF_TARGET=0.0).
Processed C02102674: 14 real entries (FPF_TARGET=0.0).
Processed C01100536: 23 real entries (FPF_TARGET=0.0).
Processed C02104240: 15 real entries (FPF_TARGET=0.0).
Processed C01103724: 18 real entries (FPF_TARGET=0.0).
Processed C02101466: 14 real entries (FPF_TARGET=0.0).
Processed C02101145: 23 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101857: 15 real entries (FPF_TARGET=0.0).
Processed C03101286: 11 real entries (FPF_TARGET=0.0).
Processed C01104762: 19 real entries (FPF_TARGET=0.0).
Processed C03102875: 22 real entries (FPF_TARGET=0.0).
Processed C01101144: 21 real entries (FPF_TARGET=0.0).
Processed C02100066: 12 real entries (FPF_TARGET=0.0).
Processed C01102324: 12 real entries (FPF_TARGET=0.0).
Processed C01104668: 22 real entries (FPF_TARGET=0.0).
Processed C01100544: 23 real entries (FPF_TARGET=0.0).
Processed C02102606: 18 real entries (FPF_TARGET=0.0).
Processed C03100686: 20 real entries (FPF_TARGET=0.0).
Processed C01103756: 8 real entries (FPF_TARGET=0.0).
Processed C02102149: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103494: 22 real entries (FPF_TARGET=0.0).
Processed C04101825: 18 real entries (FPF_TARGET=0.0).
Processed C02101414: 16 real entries (FPF_TARGET=0.0).
Processed C01104710: 19 real entries (FPF_TARGET=0.0).
Processed C02103274: 13 real entries (FPF_TARGET=0.0).
Processed C03102807: 22 real entries (FPF_TARGET=0.0).
Processed C01101136: 10 real entries (FPF_TARGET=0.0).
Processed C02100641: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104678: 23 real entries (FPF_TARGET=0.0).
Processed C04100281: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100554: 16 real entries (FPF_TARGET=0.0).
Processed C02103453: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102616: 21 real entries (FPF_TARGET=0.0).
Processed C03102817: 12 real entries (FPF_TARGET=0.0).
Processed C03100696: 16 real entries (FPF_TARGET=0.0).
Processed C01102334: 27 real entries (FPF_TARGET=0.0).
Processed C01101126: 25 real entries (FPF_TARGET=0.0).
Processed C02104405: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103746: 17 real entries (FPF_TARGET=0.0).
Processed C02102664: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103484: 18 real entries (FPF_TARGET=0.0).
Processed C04101835: 20 real entries (FPF_TARGET=0.0).
Processed C02101233: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100004: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103968: 19 real entries (FPF_TARGET=0.0).
Processed C02101404: 6 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100311: 17 real entries (FPF_TARGET=0.0).
Processed C02102053: 18 real entries (FPF_TARGET=0.0).
Processed C04103189: 21 real entries (FPF_TARGET=0.0).
Processed C01103103: 20 real entries (FPF_TARGET=0.0).
Processed C02101476: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104856: 17 real entries (FPF_TARGET=0.0).
Processed C02104467: 14 real entries (FPF_TARGET=0.0).
Processed C01102409: 11 real entries (FPF_TARGET=0.0).
Processed C04102483: 19 real entries (FPF_TARGET=0.0).
Processed C03100832: 21 real entries (FPF_TARGET=0.0).
Processed C04103810: 10 real entries (FPF_TARGET=0.0).
Processed C01100269: 25 real entries (FPF_TARGET=0.0).
Processed C01104145: 23 real entries (FPF_TARGET=0.0).
Processed C03104287: 22 real entries (FPF_TARGET=0.0).
Processed C01101763: 17 real entries (FPF_TARGET=0.0).
Processed C02100076: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100301: 20 real entries (FPF_TARGET=0.0).
Processed C04103978: 23 real entries (FPF_TARGET=0.0).
Processed C04101681: 16 real entries (FPF_TARGET=0.0).
Processed C02102043: 15 real entries (FPF_TARGET=0.0).
Processed C02104222: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102561: 22 real entries (FPF_TARGET=0.0).
Processed C01104155: 24 real entries (FPF_TARGET=0.0).
Processed C02104232: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100887: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103800: 20 real entries (FPF_TARGET=0.0).
Processed C01100279: 23 real entries (FPF_TARGET=0.0).
Processed C02104338: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101773: 15 real entries (FPF_TARGET=0.0).
Processed C04104846: 20 real entries (FPF_TARGET=0.0).
Processed C04103199: 21 real entries (FPF_TARGET=0.0).
Processed C03104297: 23 real entries (FPF_TARGET=0.0).
Processed C01103113: 19 real entries (FPF_TARGET=0.0).
Processed C01102419: 21 real entries (FPF_TARGET=0.0).
Processed C02104328: 24 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103946: 12 real entries (FPF_TARGET=0.0).
Processed C03100822: 23 real entries (FPF_TARGET=0.0).
Processed C02103206: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101251: 14 real entries (FPF_TARGET=0.0).
Processed C03104900: 18 real entries (FPF_TARGET=0.0).
Processed C01100077: 17 real entries (FPF_TARGET=0.0).
Processed C03104099: 21 real entries (FPF_TARGET=0.0).
Processed C04100964: 20 real entries (FPF_TARGET=0.0).
Processed C04103397: 21 real entries (FPF_TARGET=0.0).
Processed C02100897: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100185: 22 real entries (FPF_TARGET=0.0).
Processed C02103747: 15 real entries (FPF_TARGET=0.0).
Processed C01104223: 11 real entries (FPF_TARGET=0.0).
Processed C01101405: 3 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100896: 25 real entries (FPF_TARGET=0.0).
Processed C01103265: 23 real entries (FPF_TARGET=0.0).
Processed C03104910: 11 real entries (FPF_TARGET=0.0).
Processed C01102607: 12 real entries (FPF_TARGET=0.0).
Processed C02104669: 12 real entries (FPF_TARGET=0.0).
Processed C04103387: 23 real entries (FPF_TARGET=0.0).
Processed C02103264: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101339: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101329: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102325: 18 real entries (FPF_TARGET=0.0).
Processed C01100067: 18 real entries (FPF_TARGET=0.0).
Processed C02103421: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101137: 13 real entries (FPF_TARGET=0.0).
Processed C01100886: 14 real entries (FPF_TARGET=0.0).
Processed C01101415: 17 real entries (FPF_TARGET=0.0).
Processed C01103275: 24 real entries (FPF_TARGET=0.0).
Processed C04100195: 19 real entries (FPF_TARGET=0.0).
Processed C02102560: 14 real entries (FPF_TARGET=0.0).
Processed C01104233: 19 real entries (FPF_TARGET=0.0).
Processed C04102951: 17 real entries (FPF_TARGET=0.0).
Processed C01100622: 19 real entries (FPF_TARGET=0.0).
Processed C01101328: 23 real entries (FPF_TARGET=0.0).
Processed C01102042: 22 real entries (FPF_TARGET=0.0).
Processed C01103548: 23 real entries (FPF_TARGET=0.0).
Processed C03102380: 13 real entries (FPF_TARGET=0.0).
Processed C02100300: 13 real entries (FPF_TARGET=0.0).
Processed C04102829: 16 real entries (FPF_TARGET=0.0).
Processed C03100498: 2 real entries (FPF_TARGET=0.0).
Processed C01101250: 17 real entries (FPF_TARGET=0.0).
Processed C02103559: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103431: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101973: 24 real entries (FPF_TARGET=0.0).
Processed C01104476: 16 real entries (FPF_TARGET=0.0).
Processed C02101772: 19 real entries (FPF_TARGET=0.0).
Processed C02104154: 14 real entries (FPF_TARGET=0.0).
Processed C04101691: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103430: 22 real entries (FPF_TARGET=0.0).
Processed C01102052: 17 real entries (FPF_TARGET=0.0).
Processed C02102570: 12 real entries (FPF_TARGET=0.0).
Processed C04104594: 14 real entries (FPF_TARGET=0.0).
Processed C04102941: 22 real entries (FPF_TARGET=0.0).
Processed C01103420: 21 real entries (FPF_TARGET=0.0).
Processed C01100632: 17 real entries (FPF_TARGET=0.0).
Processed C03101963: 19 real entries (FPF_TARGET=0.0).
Processed C02100268: 11 real entries (FPF_TARGET=0.0).
Processed C02100623: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102839: 26 real entries (FPF_TARGET=0.0).
Processed C01101240: 21 real entries (FPF_TARGET=0.0).
Processed C02102335: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104466: 17 real entries (FPF_TARGET=0.0).
Processed C01100957: 17 real entries (FPF_TARGET=0.0).
Processed C03103066: 2 real entries (FPF_TARGET=0.0).
Processed C04102624: 21 real entries (FPF_TARGET=0.0).
Processed C02103686: 17 real entries (FPF_TARGET=0.0).
Processed C04104368: 22 real entries (FPF_TARGET=0.0).
Processed C02100555: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100044: 20 real entries (FPF_TARGET=0.0).
Processed C03101606: 16 real entries (FPF_TARGET=0.0).
Processed C03104020: 3 real entries (FPF_TARGET=0.0).
Processed C02104477: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100494: 8 real entries (FPF_TARGET=0.0).
Processed C04103256: 22 real entries (FPF_TARGET=0.0).
Processed C02104679: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104210: 17 real entries (FPF_TARGET=0.0).
Processed C03104158: 16 real entries (FPF_TARGET=0.0).
Processed C02101807: 18 real entries (FPF_TARGET=0.0).
Processed C03102414: 22 real entries (FPF_TARGET=0.0).
Processed C04101436: 18 real entries (FPF_TARGET=0.0).
Processed C03100274: 15 real entries (FPF_TARGET=0.0).
Processed C02101127: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101616: 23 real entries (FPF_TARGET=0.0).
Processed C04104378: 23 real entries (FPF_TARGET=0.0).
Processed C01100947: 17 real entries (FPF_TARGET=0.0).
Processed C03104030: 19 real entries (FPF_TARGET=0.0).
Processed C03100488: 7 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100264: 21 real entries (FPF_TARGET=0.0).
Processed C03103076: 24 real entries (FPF_TARGET=0.0).
Processed C02101817: 12 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102404.parquet: No valid posted_date for consumer C03102404
Processed C02100484: 15 real entries (FPF_TARGET=0.0).
Processed C04103246: 20 real entries (FPF_TARGET=0.0).
Processed C02104095: 16 real entries (FPF_TARGET=0.0).
Processed C04102071: 27 real entries (FPF_TARGET=0.0).
Processed C03103633: 7 real entries (FPF_TARGET=0.0).
Processed C03102339: 21 real entries (FPF_TARGET=0.0).
Processed C04100611: 18 real entries (FPF_TARGET=0.0).
Processed C03104675: 14 real entries (FPF_TARGET=0.0).
Processed C03104089: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101053: 23 real entries (FPF_TARGET=0.0).
Processed C01102962: 17 real entries (FPF_TARGET=0.0).
Processed C01101391: 15 real entries (FPF_TARGET=0.0).
Processed C04103403: 22 real entries (FPF_TARGET=0.0).
Processed C03102241: 19 real entries (FPF_TARGET=0.0).
Processed C02100545: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104148: 3 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102890: 19 real entries (FPF_TARGET=0.0).
Processed C04101263: 16 real entries (FPF_TARGET=0.0).
Processed C03100421: 20 real entries (FPF_TARGET=0.0).
Processed C04100601: 20 real entries (FPF_TARGET=0.0).
Processed C03100549: 17 real entries (FPF_TARGET=0.0).
Processed C01102972: 18 real entries (FPF_TARGET=0.0).
Processed C03104665: 19 real entries (FPF_TARGET=0.0).
Processed C03102329: 22 real entries (FPF_TARGET=0.0).
Processed C02102418: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104455: 19 real entries (FPF_TARGET=0.0).
Processed C04102880: 20 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03100431.parquet: No valid posted_date for consumer C03100431
Processed C04103413: 20 real entries (FPF_TARGET=0.0).
Processed C01103499: 21 real entries (FPF_TARGET=0.0).
Processed C02103822: 12 real entries (FPF_TARGET=0.0).
Processed C04102119: 17 real entries (FPF_TARGET=0.0).
Processed C02104144: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100577: 17 real entries (FPF_TARGET=0.0).
Processed C01103697: 23 real entries (FPF_TARGET=0.0).
Processed C03103555: 21 real entries (FPF_TARGET=0.0).
Processed C04101105: 16 real entries (FPF_TARGET=0.0).
Processed C04104723: 21 real entries (FPF_TARGET=0.0).
Processed C03100747: 20 real entries (FPF_TARGET=0.0).
Processed C01101816: 17 real entries (FPF_TARGET=0.0).Processed C03102127: 21 real entries (FPF_TARGET=0.0).

Processed C04103765: 17 real entries (FPF_TARGET=0.0).
Processed C04102307: 23 real entries (FPF_TARGET=0.0).
Processed C01103687: 20 real entries (FPF_TARGET=0.0).
Processed C03103545: 25 real entries (FPF_TARGET=0.0).
Processed C03104503: 7 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03101325.parquet: No valid features generated for consumer C03101325
Processed C04100567: 23 real entries (FPF_TARGET=0.0).
Processed C01101806: 17 real entries (FPF_TARGET=0.0).
Processed C02103102: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104733: 14 real entries (FPF_TARGET=0.0).
Processed C04101628: 21 real entries (FPF_TARGET=0.0).
Processed C03102137: 15 real entries (FPF_TARGET=0.0).
Processed C03104346: 17 real entries (FPF_TARGET=0.0).
Processed C03103300: 7 real entries (FPF_TARGET=0.0).
Processed C04102542: 18 real entries (FPF_TARGET=0.0).
Processed C02102973: 8 real entries (FPF_TARGET=0.0).
Processed C04104997: 20 real entries (FPF_TARGET=0.0).
Processed C02102408: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103048: 16 real entries (FPF_TARGET=0.0).
Processed C04101750: 24 real entries (FPF_TARGET=0.0).
Processed C01103823: 20 real entries (FPF_TARGET=0.0).
Processed C03101418: 20 real entries (FPF_TARGET=0.0).
Processed C04104176: 18 real entries (FPF_TARGET=0.0).
Processed C04102109: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103278: 16 real entries (FPF_TARGET=0.0).
Processed C04103130: 11 real entries (FPF_TARGET=0.0).
Processed C01104865: 10 real entries (FPF_TARGET=0.0).
Processed C02101390: 11 real entries (FPF_TARGET=0.0).
Processed C02103696: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102552: 23 real entries (FPF_TARGET=0.0).
Processed C04103058: 14 real entries (FPF_TARGET=0.0).
Processed C03104356: 14 real entries (FPF_TARGET=0.0).
Processed C04101638: 17 real entries (FPF_TARGET=0.0).
Processed C04100332: 18 real entries (FPF_TARGET=0.0).
Processed C03101570: 17 real entries (FPF_TARGET=0.0).
Processed C02101762: 22 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100278: 23 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104094: 24 real entries (FPF_TARGET=0.0).
Processed C04101740: 16 real entries (FPF_TARGET=0.0).
Processed C01104875: 16 real entries (FPF_TARGET=0.0).
Processed C03100102: 5 real entries (FPF_TARGET=0.0).
Processed C04104166: 18 real entries (FPF_TARGET=0.0).
Processed C01103833: 25 real entries (FPF_TARGET=0.0).
Processed C03103573: 20 real entries (FPF_TARGET=0.0).
Processed C03102079: 24 real entries (FPF_TARGET=0.0).
Processed C03104535: 24 real entries (FPF_TARGET=0.0).
Processed C02103832: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104200: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104874: 15 real entries and 20 simulations (FPF_TARGET=1.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C01103994: 24 real entries (FPF_TARGET=0.0).
Processed C03104389: 21 real entries (FPF_TARGET=0.0).
Processed C01102507: 24 real entries (FPF_TARGET=0.0).
Processed C02104569: 14 real entries (FPF_TARGET=0.0).
Processed C04103087: 19 real entries (FPF_TARGET=0.0).
Processed C04104958: 21 real entries (FPF_TARGET=0.0).
Processed C01100169: 22 real entries (FPF_TARGET=0.0).
Processed C04103289: 12 real entries (FPF_TARGET=0.0).
Processed C01104245: 20 real entries (FPF_TARGET=0.0).
Processed C01103203: 22 real entries (FPF_TARGET=0.0).
Processed C02103138: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102783: 18 real entries (FPF_TARGET=0.0).
Processed C01102709: 27 real entries (FPF_TARGET=0.0).
Processed C04100826: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103920: 23 real entries (FPF_TARGET=0.0).
Processed C03103814: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104006: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100417: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101039: 18 real entries (FPF_TARGET=0.0).
Processed C04103299: 16 real entries (FPF_TARGET=0.0).
Processed C03104966: 17 real entries (FPF_TARGET=0.0).
Processed C01103213: 19 real entries (FPF_TARGET=0.0).
Processed C02103128: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102719: 11 real entries (FPF_TARGET=0.0).
Processed C01100179: 12 real entries (FPF_TARGET=0.0).
Processed C01101473: 16 real entries (FPF_TARGET=0.0).
Processed C03103848: 20 real entries (FPF_TARGET=0.0).
Processed C02101748: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104197: 3 real entries (FPF_TARGET=0.0).
Processed C01100998: 18 real entries (FPF_TARGET=0.0).
Processed C02100523: 15 real entries (FPF_TARGET=0.0).
Processed C02101029: 13 real entries (FPF_TARGET=0.0).
Processed C03104976: 18 real entries (FPF_TARGET=0.0).
Processed C01102661: 12 real entries (FPF_TARGET=0.0).
Processed C01100001: 26 real entries (FPF_TARGET=0.0).
Processed C02103649: 19 real entries (FPF_TARGET=0.0).
Processed C02102343: 19 real entries (FPF_TARGET=0.0).
Processed C04101581: 13 real entries (FPF_TARGET=0.0).
Processed C03103930: 13 real entries (FPF_TARGET=0.0).
Processed C01104410: 17 real entries (FPF_TARGET=0.0).
Processed C02102025: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103721: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104767: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101236: 20 real entries (FPF_TARGET=0.0).
Processed C03103794: 5 real entries (FPF_TARGET=0.0).
Processed C02101714: 13 real entries (FPF_TARGET=0.0).
Processed C01103456: 21 real entries (FPF_TARGET=0.0).
Processed C01100644: 16 real entries (FPF_TARGET=0.0).
Processed C01104568: 8 real entries (FPF_TARGET=0.0).
Processed C04102937: 20 real entries (FPF_TARGET=0.0).
Processed C03100586: 19 real entries (FPF_TARGET=0.0).
Processed C02100010: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101915: 22 real entries (FPF_TARGET=0.0).
Processed C01102024: 23 real entries (FPF_TARGET=0.0).
Processed C02103202: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103446: 27 real entries (FPF_TARGET=0.0).
Processed C02101141: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104401: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104400: 20 real entries (FPF_TARGET=0.0).
Processed C01101226: 13 real entries (FPF_TARGET=0.0).
Processed C02101151: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103985: 10 real entries (FPF_TARGET=0.0).
Processed C02100533: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103659: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102034: 23 real entries (FPF_TARGET=0.0).
Processed C03101905: 22 real entries (FPF_TARGET=0.0).
Processed C01104578: 24 real entries (FPF_TARGET=0.0).
Processed C01100654: 23 real entries (FPF_TARGET=0.0).
Processed C04102927: 19 real entries (FPF_TARGET=0.0).
Processed C03100596: 19 real entries (FPF_TARGET=0.0).
Processed C04103230: 26 real entries (FPF_TARGET=0.0).
Processed C03103178: 19 real entries (FPF_TARGET=0.0).
Processed C03102472: 21 real entries (FPF_TARGET=0.0).
Processed C02101861: 15 real entries (FPF_TARGET=0.0).
Processed C04101450: 24 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03101718.parquet: No valid posted_date for consumer C03101718
Processed C03100212: 18 real entries (FPF_TARGET=0.0).
Processed C04104276: 21 real entries (FPF_TARGET=0.0).
Processed C02103798: 15 real entries (FPF_TARGET=0.0).
Processed C02101080: 15 real entries (FPF_TARGET=0.0).
Processed C04103348: 24 real entries (FPF_TARGET=0.0).
Processed C01100931: 11 real entries (FPF_TARGET=0.0).
Processed C04101528: 17 real entries (FPF_TARGET=0.0).
Processed C03103999: 12 real entries (FPF_TARGET=0.0).
Processed C03104046: 20 real entries (FPF_TARGET=0.0).
Processed C02103174: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104384: 9 real entries (FPF_TARGET=0.0).
Processed C04100022: 19 real entries (FPF_TARGET=0.0).
Processed C03101660: 16 real entries (FPF_TARGET=0.0).
Processed C02103731: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104266: 18 real entries (FPF_TARGET=0.0).
Processed C02103788: 23 real entries (FPF_TARGET=0.0).
Processed C03101708: 10 real entries (FPF_TARGET=0.0).
Processed C03103168: 19 real entries (FPF_TARGET=0.0).
Processed C04103220: 21 real entries (FPF_TARGET=0.0).
Processed C01100859: 22 real entries (FPF_TARGET=0.0).
Processed C03102462: 19 real entries (FPF_TARGET=0.0).
Processed C03104056: 3 real entries (FPF_TARGET=0.0).
Processed C02101909: 22 real entries (FPF_TARGET=0.0).
Processed C04100902: 23 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103989: 18 real entries (FPF_TARGET=0.0).
Processed C04100032: 21 real entries (FPF_TARGET=0.0).
Processed C03101670: 14 real entries (FPF_TARGET=0.0).
Processed C04100912: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104394: 18 real entries (FPF_TARGET=0.0).
Processed C04102652: 21 real entries (FPF_TARGET=0.0).
Processed C04103358: 11 real entries (FPF_TARGET=0.0).
Processed C01100921: 22 real entries (FPF_TARGET=0.0).
Processed C03102227: 14 real entries (FPF_TARGET=0.0).
Processed C04103465: 23 real entries (FPF_TARGET=0.0).
Processed C03100447: 25 real entries (FPF_TARGET=0.0).
Processed C02101704: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100366: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104423: 17 real entries (FPF_TARGET=0.0).
Processed C01100785: 19 real entries (FPF_TARGET=0.0).
Processed C02104812: 12 real entries (FPF_TARGET=0.0).
Processed C03103655: 17 real entries (FPF_TARGET=0.0).
Processed C01103597: 14 real entries (FPF_TARGET=0.0).
Processed C04102017: 22 real entries (FPF_TARGET=0.0).
Processed C02104122: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102904: 21 real entries (FPF_TARGET=0.0).
Processed C04100677: 18 real entries (FPF_TARGET=0.0).
Processed C04104433: 14 real entries (FPF_TARGET=0.0).
Processed C04101215: 17 real entries (FPF_TARGET=0.0).
Processed C04103475: 15 real entries (FPF_TARGET=0.0).
Processed C03100457: 16 real entries (FPF_TARGET=0.0).
Processed C02103844: 8 real entries (FPF_TARGET=0.0).
Processed C02102516: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100667: 20 real entries (FPF_TARGET=0.0).
Processed C01103587: 19 real entries (FPF_TARGET=0.0).
Processed C03102237: 21 real entries (FPF_TARGET=0.0).
Processed C04104745: 19 real entries (FPF_TARGET=0.0).
Processed C03103645: 25 real entries (FPF_TARGET=0.0).
Processed C04100469: 20 real entries (FPF_TARGET=0.0).
Processed C02100376: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103703: 10 real entries (FPF_TARGET=0.0).
Processed C01103789: 9 real entries (FPF_TARGET=0.0).
Processed C03100721: 16 real entries (FPF_TARGET=0.0).
Processed C02104132: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101353: 7 real entries (FPF_TARGET=0.0).
Processed C01102283: 20 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03104575.parquet: No valid posted_date for consumer C03104575
Processed C04100511: 28 real entries (FPF_TARGET=0.0).
Processed C03100659: 24 real entries (FPF_TARGET=0.0).
Processed C02102292: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103995: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102039: 22 real entries (FPF_TARGET=0.0).
Processed C04101982: 25 real entries (FPF_TARGET=0.0).
Processed C04102371: 18 real entries (FPF_TARGET=0.0).
Processed C04103713: 21 real entries (FPF_TARGET=0.0).
Processed C01101908: 21 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102151.parquet: No valid features generated for consumer C03102151
Processed C01103799: 20 real entries (FPF_TARGET=0.0).
Processed C01101860: 16 real entries (FPF_TARGET=0.0).
Processed C04102219: 21 real entries (FPF_TARGET=0.0).
Processed C01102293: 19 real entries (FPF_TARGET=0.0).
Processed C04104755: 11 real entries (FPF_TARGET=0.0).
Processed C04100479: 25 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102029.parquet: No valid posted_date for consumer C03102029
Processed C04101173: 20 real entries (FPF_TARGET=0.0).
Processed C04102361: 19 real entries (FPF_TARGET=0.0).
Processed C01101918: 19 real entries (FPF_TARGET=0.0).
Processed C03103523: 15 real entries (FPF_TARGET=0.0).
Processed C02102282: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102642: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104565: 19 real entries (FPF_TARGET=0.0).
Processed C01103845: 16 real entries (FPF_TARGET=0.0).
Processed C03101343: 19 real entries (FPF_TARGET=0.0).
Processed C03104258: 12 real entries (FPF_TARGET=0.0).
Processed C04104110: 20 real entries (FPF_TARGET=0.0).
Processed C04101736: 21 real entries (FPF_TARGET=0.0).
Processed C04103156: 12 real entries (FPF_TARGET=0.0).
Processed C03102714: 21 real entries (FPF_TARGET=0.0).
Processed C01104803: 23 real entries (FPF_TARGET=0.0).
Processed C02101090: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101871: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100920: 9 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100344: 18 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03100995.parquet: No valid features generated for consumer C03100995
Processed C02100784: 15 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102704.parquet: No valid features generated for consumer C03102704
Processed C04104899: 15 real entries (FPF_TARGET=0.0).
Processed C04103146: 17 real entries (FPF_TARGET=0.0).
Processed C03101506: 25 real entries (FPF_TARGET=0.0).
Processed C04101726: 25 real entries (FPF_TARGET=0.0).
Processed C03104248: 21 real entries (FPF_TARGET=0.0).
Processed C02102905: 21 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03103376.parquet: No valid features generated for consumer C03103376
Processed C03100985: 16 real entries (FPF_TARGET=0.0).
Processed C04102534: 21 real entries (FPF_TARGET=0.0).
Processed C02103596: 14 real entries (FPF_TARGET=0.0).
Processed C03101516: 15 real entries (FPF_TARGET=0.0).
Processed C03104330: 22 real entries (FPF_TARGET=0.0).
Processed C01104861: 23 real entries (FPF_TARGET=0.0).
Processed C01103827: 19 real entries (FPF_TARGET=0.0).
Processed C04104172: 8 real entries (FPF_TARGET=0.0).
Processed C04101538: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102776: 20 real entries (FPF_TARGET=0.0).
Processed C01104919: 17 real entries (FPF_TARGET=0.0).
Processed C04101205: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101754: 24 real entries (FPF_TARGET=0.0).
Processed C04104993: 20 real entries (FPF_TARGET=0.0).
Processed C04102546: 23 real entries (FPF_TARGET=0.0).
Processed C01104080: 24 real entries (FPF_TARGET=0.0).
Processed C01103837: 15 real entries (FPF_TARGET=0.0).
Processed C03100106: 22 real entries (FPF_TARGET=0.0).
Processed C04101744: 22 real entries (FPF_TARGET=0.0).
Processed C04101163: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102766: 14 real entries (FPF_TARGET=0.0).
Processed C02104395: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103124: 16 real entries (FPF_TARGET=0.0).
Processed C03101574: 11 real entries (FPF_TARGET=0.0).
Processed C01104090: 4 real entries (FPF_TARGET=0.0).
Processed C04100336: 23 real entries (FPF_TARGET=0.0).
Processed C01104909: 16 real entries (FPF_TARGET=0.0).
Processed C03104352: 21 real entries (FPF_TARGET=0.0).
Processed C04104983: 22 real entries (FPF_TARGET=0.0).
Processed C02101394: 15 real entries (FPF_TARGET=0.0).
Processed C03103314: 15 real entries (FPF_TARGET=0.0).
Processed C04102556: 19 real entries (FPF_TARGET=0.0).
Processed C03103429: 13 real entries (FPF_TARGET=0.0).
Processed C01101812: 24 real entries (FPF_TARGET=0.0).
Processed C04104727: 13 real entries (FPF_TARGET=0.0).
Processed C03101249: 19 real entries (FPF_TARGET=0.0).
Processed C01100481: 20 real entries (FPF_TARGET=0.0).
Processed C02100930: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100858: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102313: 12 real entries (FPF_TARGET=0.0).
Processed C03103551: 17 real entries (FPF_TARGET=0.0).
Processed C04100573: 17 real entries (FPF_TARGET=0.0).
Processed C03101331: 22 real entries (FPF_TARGET=0.0).
Processed C02100794: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104517: 18 real entries (FPF_TARGET=0.0).
Processed C02104385: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101079: 17 real entries (FPF_TARGET=0.0).
Processed C03101259: 17 real entries (FPF_TARGET=0.0).
Processed C01100491: 25 real entries (FPF_TARGET=0.0).
Processed C04104737: 21 real entries (FPF_TARGET=0.0).
Processed C04101111: 27 real entries (FPF_TARGET=0.0).
Processed C03100753: 14 real entries (FPF_TARGET=0.0).
Processed C04103771: 17 real entries (FPF_TARGET=0.0).
Processed C03102133: 18 real entries (FPF_TARGET=0.0).
Processed C04101888: 17 real entries (FPF_TARGET=0.0).
Processed C03103439: 15 real entries (FPF_TARGET=0.0).
Processed C01101802: 18 real entries (FPF_TARGET=0.0).
Processed C04101069: 8 real entries (FPF_TARGET=0.0).
Processed C03104507: 12 real entries (FPF_TARGET=0.0).
Processed C01103683: 18 real entries (FPF_TARGET=0.0).
Processed C04102303: 19 real entries (FPF_TARGET=0.0).
Processed C03103541: 23 real entries (FPF_TARGET=0.0).
Processed C02100848: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101267: 19 real entries (FPF_TARGET=0.0).
Processed C03100425: 20 real entries (FPF_TARGET=0.0).
Processed C04102894: 24 real entries (FPF_TARGET=0.0).
Processed C03104709: 16 real entries (FPF_TARGET=0.0).
Processed C04104441: 18 real entries (FPF_TARGET=0.0).
Processed C02103836: 16 real entries (FPF_TARGET=0.0).
Processed C03102245: 16 real entries (FPF_TARGET=0.0).
Processed C04103407: 16 real entries (FPF_TARGET=0.0).
Processed C03104671: 13 real entries (FPF_TARGET=0.0).
Processed C01101395: 20 real entries (FPF_TARGET=0.0).
Processed C02104908: 15 real entries (FPF_TARGET=0.0).
Processed C04100615: 18 real entries (FPF_TARGET=0.0).
Processed C03103637: 1 real entries (FPF_TARGET=0.0).
Processed C04100326: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104091: 15 real entries (FPF_TARGET=0.0).
Processed C04102075: 17 real entries (FPF_TARGET=0.0).
Processed C01102197: 18 real entries (FPF_TARGET=0.0).
Processed C03102255: 16 real entries (FPF_TARGET=0.0).
Processed C02103826: 10 real entries (FPF_TARGET=0.0).
Processed C02102977: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103417: 25 real entries (FPF_TARGET=0.0).
Processed C02102186: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101277: 19 real entries (FPF_TARGET=0.0).
Processed C04102884: 21 real entries (FPF_TARGET=0.0).
Processed C04104451: 15 real entries (FPF_TARGET=0.0).
Processed C03100435: 24 real entries (FPF_TARGET=0.0).
Processed C04102065: 20 real entries (FPF_TARGET=0.0).
Processed C03100731: 22 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103627: 16 real entries (FPF_TARGET=0.0).
Processed C01102976: 23 real entries (FPF_TARGET=0.0).
Processed C03104661: 18 real entries (FPF_TARGET=0.0).
Processed C04104529: 15 real entries (FPF_TARGET=0.0).
Processed C02104918: 14 real entries (FPF_TARGET=0.0).
Processed C02101803: 15 real entries (FPF_TARGET=0.0).
Processed C02102196: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101047: 13 real entries (FPF_TARGET=0.0).
Processed C03103883: 10 real entries (FPF_TARGET=0.0).
Processed C04100605: 23 real entries (FPF_TARGET=0.0).
Processed C04103252: 12 real entries (FPF_TARGET=0.0).
Processed C03104024: 14 real entries (FPF_TARGET=0.0).
Processed C04104214: 26 real entries (FPF_TARGET=0.0).
Processed C02102388: 10 real entries (FPF_TARGET=0.0).
Processed C04104889: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103682: 17 real entries (FPF_TARGET=0.0).
Processed C03102410: 15 real entries (FPF_TARGET=0.0).
Processed C03100308: 26 real entries (FPF_TARGET=0.0).
Processed C03103062: 12 real entries (FPF_TARGET=0.0).
Processed C04102620: 19 real entries (FPF_TARGET=0.0).
Processed C03102568: 17 real entries (FPF_TARGET=0.0).
Processed C01100953: 20 real entries (FPF_TARGET=0.0).
Processed C02100480: 12 real entries (FPF_TARGET=0.0).
Processed C04103242: 12 real entries (FPF_TARGET=0.0).
Processed C04102748: 18 real entries (FPF_TARGET=0.0).
Processed C04101422: 19 real entries (FPF_TARGET=0.0).
Processed C03103893: 14 real entries (FPF_TARGET=0.0).
Processed C03101602: 22 real entries (FPF_TARGET=0.0).
Processed C03102578: 13 real entries (FPF_TARGET=0.0).
Processed C04100128: 21 real entries (FPF_TARGET=0.0).
Processed C04102630: 20 real entries (FPF_TARGET=0.0).
Processed C02101384: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104034: 18 real entries (FPF_TARGET=0.0).
Processed C04100050: 26 real entries (FPF_TARGET=0.0).
Processed C03103072: 22 real entries (FPF_TARGET=0.0).
Processed C02103692: 9 real entries (FPF_TARGET=0.0).
Processed C01103434: 19 real entries (FPF_TARGET=0.0).
Processed C03101612: 24 real entries (FPF_TARGET=0.0).
Processed C02103116: 14 real entries (FPF_TARGET=0.0).
Processed C03100318: 24 real entries (FPF_TARGET=0.0).
Processed C01104472: 16 real entries (FPF_TARGET=0.0).
Processed C01101254: 23 real entries (FPF_TARGET=0.0).
Processed C02104028: 17 real entries (FPF_TARGET=0.0).
Processed C03101977: 16 real entries (FPF_TARGET=0.0).
Processed C01102046: 24 real entries (FPF_TARGET=0.0).
Processed C01100626: 22 real entries (FPF_TARGET=0.0).
Processed C01105000: 18 real entries (FPF_TARGET=0.0).
Processed C04104580: 23 real entries (FPF_TARGET=0.0).
Processed C03101186: 7 real entries (FPF_TARGET=0.0).
Processed C01104462: 24 real entries (FPF_TARGET=0.0).
Processed C04102955: 18 real entries (FPF_TARGET=0.0).
Processed C02103106: 15 real entries (FPF_TARGET=0.0).
Processed C01103424: 27 real entries (FPF_TARGET=0.0).
Processed C04101101: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103619: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100743: 18 real entries and 20 simulations (FPF_TARGET=1.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C04101072: 10 real entries (FPF_TARGET=0.0).Processed C03100630: 12 real entries (FPF_TARGET=0.0).

Processed C04104654: 19 real entries (FPF_TARGET=0.0).
Processed C04100578: 21 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C01103698: 24 real entries (FPF_TARGET=0.0).
Processed C02101902: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102050: 23 real entries (FPF_TARGET=0.0).
Processed C03104157: 14 real entries and 20 simulations (FPF_TARGET=1.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C01101809: 19 real entries (FPF_TARGET=0.0).
Processed C03103432: 21 real entries (FPF_TARGET=0.0).
Processed C02102289: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101883: 21 real entries (FPF_TARGET=0.0).
Processed C04102270: 22 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C03102138: 22 real entries (FPF_TARGET=0.0).
Processed C03104474: 2 real entries (FPF_TARGET=0.0).
Processed C04101523: 23 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101190: 26 real entries (FPF_TARGET=0.0).
Processed C04100410: 16 real entries (FPF_TARGET=0.0).
Processed C03101252: 19 real entries (FPF_TARGET=0.0).
Processed C01102382: 15 real entries (FPF_TARGET=0.0).
Processed C01101971: 20 real entries (FPF_TARGET=0.0).
Processed C01103688: 14 real entries (FPF_TARGET=0.0).
Processed C04102308: 26 real entries (FPF_TARGET=0.0).
Processed C04103602: 19 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C03100620: 16 real entries (FPF_TARGET=0.0).
Processed C02101191: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102040: 22 real entries (FPF_TARGET=0.0).
Processed C04100568: 12 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C04104644: 19 real entries (FPF_TARGET=0.0).
Processed C03104231: 22 real entries (FPF_TARGET=0.0).
Processed C04104179: 17 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C02103699: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100255: 18 real entries (FPF_TARGET=0.0).
Processed C04102435: 23 real entries (FPF_TARGET=0.0).
Processed C03100884: 18 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()
/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C03103277: 20 real entries (FPF_TARGET=0.0).
Processed C02103945: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100065: 15 real entries (FPF_TARGET=0.0).
Processed C02101818: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103954: 23 real entries (FPF_TARGET=0.0).
Processed C03102605: 7 real entries (FPF_TARGET=0.0).
Processed C04103047: 22 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C04104998: 18 real entries (FPF_TARGET=0.0).
Processed C02100831: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104912: 19 real entries (FPF_TARGET=0.0).
Processed C03103267: 12 real entries (FPF_TARGET=0.0).
Processed C03104221: 2 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C03101407: 22 real entries (FPF_TARGET=0.0).
Processed C04104169: 18 real entries (FPF_TARGET=0.0).
Processed C02103487: 11 real entries (FPF_TARGET=0.0).
Processed C01104902: 19 real entries (FPF_TARGET=0.0).
Processed C02100695: 13 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C04101314: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103057: 22 real entries (FPF_TARGET=0.0).
Processed C02100949: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101637: 19 real entries (FPF_TARGET=0.0).
Processed C03102615: 21 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C01103944: 22 real entries (FPF_TARGET=0.0).
Processed C02104903: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104359: 21 real entries (FPF_TARGET=0.0).
Processed C03100075: 22 real entries (FPF_TARGET=0.0).
Processed C02104294: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103759: 22 real entries (FPF_TARGET=0.0).
Processed C03102808: 21 real entries (FPF_TARGET=0.0).
Processed C01102253: 27 real entries (FPF_TARGET=0.0).
Processed C04104795: 20 real entries (FPF_TARGET=0.0).
Processed C02102771: 15 real entries (FPF_TARGET=0.0).
Processed C03102191: 23 real entries (FPF_TARGET=0.0).
Processed C02104345: 14 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C01104667: 15 real entries (FPF_TARGET=0.0).Processed C01101139: 23 real entries (FPF_TARGET=0.0).

Processed C03100689: 15 real entries (FPF_TARGET=0.0).
Processed C03102970: 19 real entries (FPF_TARGET=0.0).
Processed C03101383: 15 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C01100423: 22 real entries (FPF_TARGET=0.0).
Processed C04104785: 19 real entries (FPF_TARGET=0.0).
Processed C01101129: 17 real entries (FPF_TARGET=0.0).
Processed C03102818: 17 real entries (FPF_TARGET=0.0).
Processed C02102761: 16 real entries (FPF_TARGET=0.0).
Processed C01103749: 13 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C01102243: 14 real entries (FPF_TARGET=0.0).
Processed C03102960: 11 real entries (FPF_TARGET=0.0).
Processed C03102181: 16 real entries (FPF_TARGET=0.0).
Processed C03101393: 8 real entries (FPF_TARGET=0.0).
Processed C01104677: 15 real entries (FPF_TARGET=0.0).
Processed C02102619: 10 real entries (FPF_TARGET=0.0).
Processed C02103313: 18 real entries (FPF_TARGET=0.0).
Processed C03100699: 7 real entries (FPF_TARGET=0.0).
Processed C01101051: 23 real entries (FPF_TARGET=0.0).
Processed C02100079: 12 real entries (FPF_TARGET=0.0).
Processed C01103631: 22 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C04101942: 19 real entries (FPF_TARGET=0.0).
Processed C02101573: 15 real entries (FPF_TARGET=0.0).
Processed C04103186: 17 real entries (FPF_TARGET=0.0).
Processed C04104859: 15 real entries (FPF_TARGET=0.0).
Processed C02104468: 19 real entries (FPF_TARGET=0.0).
Processed C01103895: 15 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C02102124: 20 real entries (FPF_TARGET=0.0).
Processed C02104510: 17 real entries (FPF_TARGET=0.0).
Processed C04104921: 20 real entries (FPF_TARGET=0.0).
Processed C03104288: 23 real entries (FPF_TARGET=0.0).
Processed C02101336: 17 real entries (FPF_TARGET=0.0).
Processed C03100945: 10 real entries (FPF_TARGET=0.0).
Processed C02100821: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103967: 19 real entries (FPF_TARGET=0.0).
Processed C01104032: 22 real entries (FPF_TARGET=0.0).
Processed C04100394: 19 real entries (FPF_TARGET=0.0).
Processed C02103556: 16 real entries (FPF_TARGET=0.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C02102134: 12 real entries (FPF_TARGET=0.0).
Processed C03103422: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104478: 18 real entries (FPF_TARGET=0.0).
Processed C03104298: 20 real entries (FPF_TARGET=0.0).
Processed C04103196: 26 real entries (FPF_TARGET=0.0).
Processed C01102416: 20 real entries (FPF_TARGET=0.0).Processed C04104849: 24 real entries (FPF_TARGET=0.0).

Processed C01104022: 20 real entries (FPF_TARGET=0.0).
Processed C02100959: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101604: 15 real entries (FPF_TARGET=0.0).
Processed C04103977: 23 real entries (FPF_TARGET=0.0).
Processed C01103064: 4 real entries (FPF_TARGET=0.0).
Processed C03100955: 4 real entries (FPF_TARGET=0.0).
Processed C04104931: 22 real entries (FPF_TARGET=0.0).
Processed C02104500: 18 real entries (FPF_TARGET=0.0).
Processed C02103748: 11 real entries (FPF_TARGET=0.0).
Processed C02101326: 15 real entries (FPF_TARGET=0.0).
Processed C04101480: 16 real entries (FPF_TARGET=0.0).
Processed C01100100: 22 real entries (FPF_TARGET=0.0).
Processed C02101128: 18 real entries (FPF_TARGET=0.0).
Processed C01102760: 20 real entries (FPF_TARGET=0.0).
Processed C04100813: 21 real entries (FPF_TARGET=0.0).
Processed C03104096: 16 real entries (FPF_TARGET=0.0).
Processed C03103949: 19 real entries (FPF_TARGET=0.0).Processed C02103630: 15 real entries (FPF_TARGET=0.0).
Processed C01104354: 25 real entries (FPF_TARGET=0.0).

Processed C01102618: 22 real entries (FPF_TARGET=0.0).
Processed C04102692: 16 real entries (FPF_TARGET=0.0).
Processed C02101138: 20 real entries (FPF_TARGET=0.0).
Processed C04103398: 25 real entries (FPF_TARGET=0.0).
Processed C01102770: 20 real entries (FPF_TARGET=0.0).
Processed C02100432: 19 real entries (FPF_TARGET=0.0).
Processed C01100889: 22 real entries (FPF_TARGET=0.0).
Processed C04101490: 23 real entries (FPF_TARGET=0.0).
Processed C02103758: 10 real entries (FPF_TARGET=0.0).
Processed C01100110: 24 real entries (FPF_TARGET=0.0).
Processed C01102608: 17 real entries (FPF_TARGET=0.0).
Processed C02102804: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102682: 18 real entries (FPF_TARGET=0.0).
Processed C02101040: 14 real entries (FPF_TARGET=0.0).
Processed C01103302: 11 real entries (FPF_TARGET=0.0).
Processed C04103388: 16 real entries (FPF_TARGET=0.0).
Processed C01101562: 18 real entries (FPF_TARGET=0.0).
Processed C02103620: 11 real entries (FPF_TARGET=0.0).
Processed C01104344: 17 real entries (FPF_TARGET=0.0).
Processed C03103959: 21 real entries (FPF_TARGET=0.0).
Processed C03104086: 22 real entries (FPF_TARGET=0.0).
Processed C01100068: 19 real entries (FPF_TARGET=0.0).
Processed C03100497: 12 real entries (FPF_TARGET=0.0).
Processed C04102826: 19 real entries (FPF_TARGET=0.0).
Processed C01100755: 22 real entries (FPF_TARGET=0.0).
Processed C02103497: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104479: 22 real entries (FPF_TARGET=0.0).
Processed C04103612: 22 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102135: 15 real entries (FPF_TARGET=0.0).
Processed C02100277: 17 real entries (FPF_TARGET=0.0).
Processed C01101327: 10 real entries (FPF_TARGET=0.0).
Processed C01104501: 17 real entries (FPF_TARGET=0.0).
Processed C03101804: 23 real entries (FPF_TARGET=0.0).
Processed C01102125: 17 real entries (FPF_TARGET=0.0).
Processed C02103894: 7 real entries (FPF_TARGET=0.0).
Processed C04102836: 17 real entries (FPF_TARGET=0.0).
Processed C02102814: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100487: 1 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102609: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103695: 4 real entries (FPF_TARGET=0.0).
Processed C01104469: 20 real entries (FPF_TARGET=0.0).
Processed C01104511: 14 real entries (FPF_TARGET=0.0).
Processed C04101062: 23 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101179: 17 real entries (FPF_TARGET=0.0).
Processed C04104417: 10 real entries (FPF_TARGET=0.0).
Processed C03100473: 17 real entries (FPF_TARGET=0.0).
Processed C01102848: 18 real entries (FPF_TARGET=0.0).
Processed C04101231: 13 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102213.parquet: No valid features generated for consumer C03102213
Processed C04103451: 14 real entries (FPF_TARGET=0.0).
Processed C02100898: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101799: 12 real entries (FPF_TARGET=0.0).
Processed C03103719: 10 real entries (FPF_TARGET=0.0).
Processed C04100245: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101001: 22 real entries (FPF_TARGET=0.0).
Processed C04100643: 16 real entries (FPF_TARGET=0.0).
Processed C01102930: 23 real entries (FPF_TARGET=0.0).
Processed C04101349: 19 real entries (FPF_TARGET=0.0).
Processed C03104627: 2 real entries (FPF_TARGET=0.0).
Processed C02103546: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101998: 2 real entries (FPF_TARGET=0.0).
Processed C04103529: 22 real entries (FPF_TARGET=0.0).
Processed C03103661: 20 real entries (FPF_TARGET=0.0).
Processed C04102023: 17 real entries (FPF_TARGET=0.0).
Processed C02100754: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100069: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102203: 22 real entries (FPF_TARGET=0.0).
Processed C04103441: 16 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03103709.parquet: No valid features generated for consumer C03103709
Processed C02103065: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101169: 22 real entries (FPF_TARGET=0.0).
Processed C02104836: 10 real entries (FPF_TARGET=0.0).
Processed C03100463: 20 real entries (FPF_TARGET=0.0).
Processed C03101988: 10 real entries (FPF_TARGET=0.0).
Processed C04103539: 12 real entries (FPF_TARGET=0.0).
Processed C03103671: 15 real entries (FPF_TARGET=0.0).
Processed C04102033: 23 real entries (FPF_TARGET=0.0).
Processed C03101011: 23 real entries (FPF_TARGET=0.0).
Processed C02104023: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104637: 6 real entries (FPF_TARGET=0.0).
Processed C02104676: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101464: 14 real entries (FPF_TARGET=0.0).
Processed C04101359: 22 real entries (FPF_TARGET=0.0).
Processed C04104242: 16 real entries (FPF_TARGET=0.0).
Processed C03102446: 10 real entries (FPF_TARGET=0.0).
Processed C02103075: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100226: 20 real entries (FPF_TARGET=0.0).
Processed C03104893: 12 real entries (FPF_TARGET=0.0).
Processed C04100016: 20 real entries (FPF_TARGET=0.0).
Processed C01101596: 17 real entries (FPF_TARGET=0.0).
Processed C02104692: 12 real entries (FPF_TARGET=0.0).
Processed C02102417: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104072: 26 real entries (FPF_TARGET=0.0).
Processed C01100905: 21 real entries (FPF_TARGET=0.0).
Processed C04102676: 18 real entries (FPF_TARGET=0.0).
Processed C04103214: 24 real entries (FPF_TARGET=0.0).
Processed C02100293: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102456: 20 real entries (FPF_TARGET=0.0).
Processed C04104252: 19 real entries (FPF_TARGET=0.0).
Processed C01102794: 20 real entries (FPF_TARGET=0.0).
Processed C03103034: 1 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101474: 20 real entries (FPF_TARGET=0.0).
Processed C02104033: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100236: 9 real entries (FPF_TARGET=0.0).
Processed C01100915: 23 real entries (FPF_TARGET=0.0).
Processed C04100006: 22 real entries (FPF_TARGET=0.0).
Processed C03103024: 14 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03101644.parquet: No valid features generated for consumer C03101644
Processed C02102407: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101586: 17 real entries (FPF_TARGET=0.0).
Processed C04102468: 20 real entries (FPF_TARGET=0.0).
Processed C04101702: 15 real entries (FPF_TARGET=0.0).
Processed C04104124: 15 real entries (FPF_TARGET=0.0).
Processed C03100140: 17 real entries (FPF_TARGET=0.0).
Processed C03102720: 24 real entries (FPF_TARGET=0.0).
Processed C03103352: 13 real entries (FPF_TARGET=0.0).
Processed C01100282: 14 real entries (FPF_TARGET=0.0).
Processed C01103871: 18 real entries (FPF_TARGET=0.0).
Processed C01103090: 20 real entries (FPF_TARGET=0.0).
Processed C04102510: 19 real entries (FPF_TARGET=0.0).
Processed C03104314: 16 real entries (FPF_TARGET=0.0).
Processed C03101532: 12 real entries (FPF_TARGET=0.0).
Processed C04103983: 8 real entries (FPF_TARGET=0.0).
Processed C04100370: 16 real entries (FPF_TARGET=0.0).
Processed C03102658: 21 real entries (FPF_TARGET=0.0).
Processed C03100150: 4 real entries (FPF_TARGET=0.0).
Processed C02103884: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103861: 18 real entries (FPF_TARGET=0.0).
Processed C01100292: 21 real entries (FPF_TARGET=0.0).
Processed C02102849: 16 real entries (FPF_TARGET=0.0).
Processed C04100218: 17 real entries (FPF_TARGET=0.0).
Processed C04102478: 13 real entries (FPF_TARGET=0.0).
Processed C03102730: 19 real entries (FPF_TARGET=0.0).
Processed C01104827: 25 real entries (FPF_TARGET=0.0).
Processed C01101798: 26 real entries (FPF_TARGET=0.0).
Processed C04100360: 16 real entries (FPF_TARGET=0.0).
Processed C03101522: 24 real entries (FPF_TARGET=0.0).
Processed C04103993: 21 real entries (FPF_TARGET=0.0).
Processed C01103080: 17 real entries (FPF_TARGET=0.0).
Processed C04102500: 22 real entries (FPF_TARGET=0.0).
Processed C03103342: 21 real entries (FPF_TARGET=0.0).
Processed C01101844: 16 real entries (FPF_TARGET=0.0).
Processed C03100715: 8 real entries (FPF_TARGET=0.0).
Processed C02102795: 15 real entries (FPF_TARGET=0.0).
Processed C02103081: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101157: 21 real entries (FPF_TARGET=0.0).
Processed C03102175: 12 real entries (FPF_TARGET=0.0).
Processed C02103870: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102345: 18 real entries (FPF_TARGET=0.0).
Processed C03103507: 23 real entries (FPF_TARGET=0.0).
Processed C03104541: 9 real entries (FPF_TARGET=0.0).
Processed C03101367: 10 real entries (FPF_TARGET=0.0).
Processed C03102994: 20 real entries (FPF_TARGET=0.0).
Processed C01104683: 21 real entries (FPF_TARGET=0.0).
Processed C04104609: 20 real entries (FPF_TARGET=0.0).
Processed C03100705: 10 real entries (FPF_TARGET=0.0).
Processed C01101854: 14 real entries (FPF_TARGET=0.0).
Processed C04104761: 20 real entries (FPF_TARGET=0.0).
Processed C03104551: 6 real entries (FPF_TARGET=0.0).Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03101377.parquet: No valid posted_date for consumer C03101377

Processed C04103727: 25 real entries (FPF_TARGET=0.0).
Processed C04100535: 23 real entries (FPF_TARGET=0.0).
Processed C03102165: 16 real entries (FPF_TARGET=0.0).
Processed C04102355: 11 real entries (FPF_TARGET=0.0).
Processed C03103517: 10 real entries (FPF_TARGET=0.0).
Processed C03102984: 19 real entries (FPF_TARGET=0.0).
Processed C01104117: 22 real entries (FPF_TARGET=0.0).
Processed C02103473: 11 real entries (FPF_TARGET=0.0).
Processed C02100719: 14 real entries (FPF_TARGET=0.0).
Processed C02102179: 18 real entries (FPF_TARGET=0.0).
Processed C02100283: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102799: 14 real entries (FPF_TARGET=0.0).
Processed C03103293: 17 real entries (FPF_TARGET=0.0).
Processed C01103151: 24 real entries (FPF_TARGET=0.0).
Processed C03100860: 7 real entries (FPF_TARGET=0.0).
Processed C03100081: 2 real entries (FPF_TARGET=0.0).
Processed C01100343: 22 real entries (FPF_TARGET=0.0).
Processed C01101649: 22 real entries (FPF_TARGET=0.0).
Processed C01103029: 20 real entries (FPF_TARGET=0.0).
Processed C03104883: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101654: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100918: 22 real entries (FPF_TARGET=0.0).
Processed C01102523: 18 real entries (FPF_TARGET=0.0).
Processed C01103141: 18 real entries (FPF_TARGET=0.0).
Processed C02104425: 16 real entries (FPF_TARGET=0.0).
Processed C03102789: 21 real entries (FPF_TARGET=0.0).
Processed C04104814: 13 real entries (FPF_TARGET=0.0).
Processed C02101789: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104682: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103852: 20 real entries (FPF_TARGET=0.0).
Processed C03103283: 16 real entries (FPF_TARGET=0.0).
Processed C01104107: 6 real entries (FPF_TARGET=0.0).
Processed C02101845: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103918: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100870: 22 real entries (FPF_TARGET=0.0).
Processed C03100908: 4 real entries (FPF_TARGET=0.0).
Processed C01103039: 22 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03100091.parquet: No valid features generated for consumer C03100091
Processed C01100353: 23 real entries (FPF_TARGET=0.0).
Processed C03102855: 20 real entries (FPF_TARGET=0.0).
Processed C01104742: 21 real entries (FPF_TARGET=0.0).
Processed C01101164: 26 real entries (FPF_TARGET=0.0).
Processed C01103704: 20 real entries (FPF_TARGET=0.0).
Processed C01102784: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102785: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101877: 17 real entries (FPF_TARGET=0.0).
Processed C01100516: 18 real entries (FPF_TARGET=0.0).
Processed C04101096: 22 real entries (FPF_TARGET=0.0).
Processed C02102654: 15 real entries (FPF_TARGET=0.0).
Processed C02100661: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102376: 17 real entries (FPF_TARGET=0.0).
Processed C02100904: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101597: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103714: 22 real entries (FPF_TARGET=0.0).
Processed C04101867: 19 real entries (FPF_TARGET=0.0).
Processed C02101456: 15 real entries (FPF_TARGET=0.0).
Processed C02102998: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103463: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103236: 11 real entries (FPF_TARGET=0.0).
Processed C01104752: 24 real entries (FPF_TARGET=0.0).
Processed C03102845: 19 real entries (FPF_TARGET=0.0).
Processed C01101174: 23 real entries (FPF_TARGET=0.0).
Processed C02104308: 15 real entries (FPF_TARGET=0.0).
Processed C02100024: 17 real entries (FPF_TARGET=0.0).
Processed C01102366: 12 real entries (FPF_TARGET=0.0).
Processed C03104490: 21 real entries (FPF_TARGET=0.0).
Processed C01101995: 24 real entries (FPF_TARGET=0.0).
Processed C01100506: 28 real entries (FPF_TARGET=0.0).
Processed C03101859: 9 real entries (FPF_TARGET=0.0).
Processed C04101086: 22 real entries (FPF_TARGET=0.0).
Processed C02104435: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103462: 22 real entries (FPF_TARGET=0.0).
Processed C01101202: 19 real entries (FPF_TARGET=0.0).
Processed C02104106: 22 real entries (FPF_TARGET=0.0).
Processed C04101288: 16 real entries (FPF_TARGET=0.0).
Processed C01100708: 21 real entries (FPF_TARGET=0.0).
Processed C02103140: 21 real entries (FPF_TARGET=0.0).
Processed C04100782: 21 real entries (FPF_TARGET=0.0).
Processed C01104424: 25 real entries (FPF_TARGET=0.0).
Processed C01102010: 20 real entries (FPF_TARGET=0.0).
Processed C02100352: 19 real entries (FPF_TARGET=0.0).
Processed C04103590: 15 real entries (FPF_TARGET=0.0).
Processed C03101921: 20 real entries (FPF_TARGET=0.0).
Processed C02102532: 16 real entries (FPF_TARGET=0.0).
Processed C02102001: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100670: 21 real entries (FPF_TARGET=0.0).
Processed C04101298: 10 real entries (FPF_TARGET=0.0).
Processed C01101212: 25 real entries (FPF_TARGET=0.0).
Processed C01104434: 21 real entries (FPF_TARGET=0.0).
Processed C01100718: 13 real entries (FPF_TARGET=0.0).
Processed C04100792: 23 real entries (FPF_TARGET=0.0).
Processed C01102178: 22 real entries (FPF_TARGET=0.0).
Processed C02101446: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102169: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103472: 21 real entries (FPF_TARGET=0.0).
Processed C01102999: 14 real entries (FPF_TARGET=0.0).
Processed C01100660: 21 real entries (FPF_TARGET=0.0).
Processed C04102913: 26 real entries (FPF_TARGET=0.0).
Processed C02104260: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103028: 16 real entries (FPF_TARGET=0.0).
Processed C03101931: 16 real entries (FPF_TARGET=0.0).
Processed C01102000: 23 real entries (FPF_TARGET=0.0).
Processed C04103580: 14 real entries (FPF_TARGET=0.0).
Processed C02104753: 14 real entries (FPF_TARGET=0.0).
Processed C02103226: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103237: 15 real entries (FPF_TARGET=0.0).
Processed C01101457: 18 real entries (FPF_TARGET=0.0).
Processed C01104271: 23 real entries (FPF_TARGET=0.0).
Processed C03101795: 26 real entries (FPF_TARGET=0.0).
Processed C02100709: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102645: 14 real entries (FPF_TARGET=0.0).
Processed C04100936: 20 real entries (FPF_TARGET=0.0).
Processed C02102011: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101994: 14 real entries (FPF_TARGET=0.0).
Processed C02102367: 20 real entries (FPF_TARGET=0.0).
Processed C03103914: 22 real entries (FPF_TARGET=0.0).
Processed C04104383: 22 real entries (FPF_TARGET=0.0).
Processed C01104309: 22 real entries (FPF_TARGET=0.0).
Processed C01101447: 21 real entries (FPF_TARGET=0.0).
Processed C03102587: 2 real entries and 20 simulations (FPF_TARGET=1.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03101785.parquet: No valid features generated for consumer C03101785
Processed C02103705: 14 real entries (FPF_TARGET=0.0).
Processed C01104261: 13 real entries (FPF_TARGET=0.0).
Processed C01103227: 26 real entries (FPF_TARGET=0.0).
Processed C02104743: 14 real entries (FPF_TARGET=0.0).
Processed C03103904: 19 real entries (FPF_TARGET=0.0).
Processed C04104393: 23 real entries (FPF_TARGET=0.0).
Processed C01104319: 20 real entries (FPF_TARGET=0.0).
Processed C01102655: 25 real entries (FPF_TARGET=0.0).
Processed C03104942: 17 real entries (FPF_TARGET=0.0).
Processed C02100517: 13 real entries (FPF_TARGET=0.0).
Processed C04100926: 23 real entries (FPF_TARGET=0.0).
Processed C03102597: 13 real entries (FPF_TARGET=0.0).
Processed C01101435: 20 real entries (FPF_TARGET=0.0).
Processed C04104299: 26 real entries (FPF_TARGET=0.0).
Processed C01104213: 20 real entries (FPF_TARGET=0.0).
Processed C03103197: 19 real entries (FPF_TARGET=0.0).
Processed C03104848: 9 real entries (FPF_TARGET=0.0).
Processed C02104270: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103255: 23 real entries (FPF_TARGET=0.0).
Processed C02101648: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102305: 14 real entries (FPF_TARGET=0.0).
Processed C01100047: 14 real entries (FPF_TARGET=0.0).
Processed C03104930: 20 real entries (FPF_TARGET=0.0).
Processed C01102627: 22 real entries (FPF_TARGET=0.0).
Processed C04100954: 22 real entries (FPF_TARGET=0.0).Processed C02104116: 12 real entries and 20 simulations (FPF_TARGET=1.0).

Processed C02103150: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103038: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104318: 20 real entries and 20 simulations (FPF_TARGET=1.0).

/var/folders/vb/p9mktqwx0rg59m22m1fdfbk80000gn/T/ipykernel_75629/683539865.py:13: RuntimeWarning: invalid value encountered in divide
  power_norm = power / power.sum()

Processed C03102270: 21 real entries (FPF_TARGET=0.0).
Processed C03100410: 19 real entries (FPF_TARGET=0.0).
Processed C04101252: 21 real entries (FPF_TARGET=0.0).
Processed C02102490: 18 real entries (FPF_TARGET=0.0).
Processed C02104845: 19 real entries (FPF_TARGET=0.0).
Processed C04104474: 21 real entries (FPF_TARGET=0.0).
Processed C03104998: 8 real entries (FPF_TARGET=0.0).
Processed C04100065: 24 real entries (FPF_TARGET=0.0).
Processed C03103047: 5 real entries (FPF_TARGET=0.0).
Processed C04102605: 12 real entries (FPF_TARGET=0.0).
Processed C02102930: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100976: 20 real entries (FPF_TARGET=0.0).
Processed C01103385: 19 real entries (FPF_TARGET=0.0).
Processed C03104179: 20 real entries (FPF_TARGET=0.0).
Processed C04104231: 22 real entries (FPF_TARGET=0.0).Processed C03100255: 20 real entries (FPF_TARGET=0.0).

Processed C03102435: 2 real entries (FPF_TARGET=0.0).
Processed C01100197: 22 real entries (FPF_TARGET=0.0).
Processed C04100884: 21 real entries (FPF_TARGET=0.0).
Processed C03103057: 22 real entries (FPF_TARGET=0.0).
Processed C04102615: 18 real entries (FPF_TARGET=0.0).
Processed C01103395: 23 real entries (FPF_TARGET=0.0).
Processed C04104359: 21 real entries (FPF_TARGET=0.0).
Processed C03101637: 5 real entries (FPF_TARGET=0.0).
Processed C04100075: 25 real entries (FPF_TARGET=0.0).
Processed C02100915: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103267: 19 real entries (FPF_TARGET=0.0).
Processed C03104169: 2 real entries (FPF_TARGET=0.0).
Processed C03100245: 2 real entries (FPF_TARGET=0.0).
Processed C04101407: 11 real entries (FPF_TARGET=0.0).
Processed C02102848: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104221: 20 real entries (FPF_TARGET=0.0).
Processed C01100187: 25 real entries (FPF_TARGET=0.0).
Processed C04100689: 22 real entries (FPF_TARGET=0.0).
Processed C01102063: 21 real entries (FPF_TARGET=0.0).
Processed C02104994: 17 real entries (FPF_TARGET=0.0).
Processed C01100603: 18 real entries (FPF_TARGET=0.0).
Processed C04102970: 8 real entries (FPF_TARGET=0.0).
Processed C04101383: 18 real entries (FPF_TARGET=0.0).
Processed C02104175: 15 real entries (FPF_TARGET=0.0).
Processed C01103411: 10 real entries (FPF_TARGET=0.0).
Processed C02100259: 11 real entries (FPF_TARGET=0.0).
Processed C02101753: 18 real entries (FPF_TARGET=0.0).
Processed C04102191: 18 real entries (FPF_TARGET=0.0).
Processed C02103394: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104457: 17 real entries (FPF_TARGET=0.0).
Processed C02103133: 16 real entries (FPF_TARGET=0.0).
Processed C04102808: 17 real entries (FPF_TARGET=0.0).
Processed C01101271: 21 real entries (FPF_TARGET=0.0).
Processed C04100699: 13 real entries (FPF_TARGET=0.0).
Processed C03104795: 25 real entries (FPF_TARGET=0.0).
Processed C01102882: 25 real entries (FPF_TARGET=0.0).
Processed C01100613: 17 real entries (FPF_TARGET=0.0).
Processed C02102551: 15 real entries (FPF_TARGET=0.0).
Processed C04101393: 15 real entries (FPF_TARGET=0.0).
Processed C04102960: 18 real entries (FPF_TARGET=0.0).
Processed C03101439: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103579: 19 real entries (FPF_TARGET=0.0).
Processed C01101319: 22 real entries (FPF_TARGET=0.0).
Processed C01102073: 21 real entries (FPF_TARGET=0.0).
Processed C04102818: 19 real entries (FPF_TARGET=0.0).
Processed C03101942: 25 real entries (FPF_TARGET=0.0).
Processed C02100967: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101261: 19 real entries (FPF_TARGET=0.0).
Processed C02102429: 19 real entries (FPF_TARGET=0.0).
Processed C01102892: 20 real entries (FPF_TARGET=0.0).
Processed C02100249: 15 real entries (FPF_TARGET=0.0).
Processed C02104165: 10 real entries (FPF_TARGET=0.0).
Processed C01103401: 19 real entries (FPF_TARGET=0.0).
Processed C04102181: 19 real entries (FPF_TARGET=0.0).
Processed C02101743: 16 real entries (FPF_TARGET=0.0).
Processed C03104785: 20 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03104921.parquet: No valid posted_date for consumer C03104921
Processed C04100945: 24 real entries (FPF_TARGET=0.0).
Processed C02100574: 18 real entries (FPF_TARGET=0.0).
Processed C01102636: 19 real entries (FPF_TARGET=0.0).
Processed C02102314: 18 real entries (FPF_TARGET=0.0).
Processed C01100056: 17 real entries (FPF_TARGET=0.0).
Processed C03103967: 15 real entries (FPF_TARGET=0.0).
Processed C02104720: 20 real entries (FPF_TARGET=0.0).
Processed C03100394: 16 real entries (FPF_TARGET=0.0).
Processed C03104859: 18 real entries (FPF_TARGET=0.0).
Processed C03103186: 24 real entries (FPF_TARGET=0.0).
Processed C02101682: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104288: 15 real entries (FPF_TARGET=0.0).
Processed C01101424: 16 real entries (FPF_TARGET=0.0).
Processed C03103977: 15 real entries (FPF_TARGET=0.0).
Processed C02104597: 20 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100046: 23 real entries (FPF_TARGET=0.0).
Processed C04101134: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100955: 22 real entries (FPF_TARGET=0.0).
Processed C02101826: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104931: 10 real entries (FPF_TARGET=0.0).
Processed C01102626: 19 real entries (FPF_TARGET=0.0).
Processed C01104212: 21 real entries (FPF_TARGET=0.0).
Processed C04104298: 18 real entries (FPF_TARGET=0.0).
Processed C02103813: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101434: 25 real entries (FPF_TARGET=0.0).
Processed C01103254: 13 real entries (FPF_TARGET=0.0).
Processed C02104855: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101116: 10 real entries (FPF_TARGET=0.0).
Processed C03104849: 16 real entries (FPF_TARGET=0.0).
Processed C02102072: 20 real entries (FPF_TARGET=0.0).
Processed C03103196: 21 real entries (FPF_TARGET=0.0).
Processed C04103949: 14 real entries (FPF_TARGET=0.0).
Processed C04104096: 22 real entries (FPF_TARGET=0.0).
Processed C01100330: 24 real entries (FPF_TARGET=0.0).
Processed C01102550: 24 real entries (FPF_TARGET=0.0).
Processed C03102692: 11 real entries (FPF_TARGET=0.0).
Processed C03103398: 21 real entries (FPF_TARGET=0.0).
Processed C01104985: 23 real entries (FPF_TARGET=0.0).
Processed C01101742: 20 real entries (FPF_TARGET=0.0).
Processed C02103400: 19 real entries (FPF_TARGET=0.0).
Processed C04103277: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101480: 11 real entries (FPF_TARGET=0.0).
Processed C01104164: 17 real entries (FPF_TARGET=0.0).
Processed C01102428: 19 real entries (FPF_TARGET=0.0).
Processed C03100813: 19 real entries (FPF_TARGET=0.0).
Processed C02102893: 13 real entries (FPF_TARGET=0.0).
Processed C02101260: 13 real entries (FPF_TARGET=0.0).
Processed C01103122: 20 real entries (FPF_TARGET=0.0).
Processed C02104446: 17 real entries (FPF_TARGET=0.0).
Processed C02101308: 20 real entries (FPF_TARGET=0.0).
Processed C03103388: 24 real entries (FPF_TARGET=0.0).
Processed C01104995: 20 real entries (FPF_TARGET=0.0).
Processed C03102682: 7 real entries (FPF_TARGET=0.0).
Processed C02102062: 17 real entries (FPF_TARGET=0.0).
Processed C04104086: 20 real entries (FPF_TARGET=0.0).
Processed C02103766: 8 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103568: 12 real entries (FPF_TARGET=0.0).
Processed C01100320: 20 real entries (FPF_TARGET=0.0).
Processed C04103959: 21 real entries (FPF_TARGET=0.0).
Processed C02104799: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102883: 14 real entries (FPF_TARGET=0.0).
Processed C01102438: 25 real entries (FPF_TARGET=0.0).
Processed C01103132: 22 real entries (FPF_TARGET=0.0).
Processed C01101752: 22 real entries (FPF_TARGET=0.0).
Processed C01100258: 21 real entries (FPF_TARGET=0.0).
Processed C02104789: 19 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104174: 7 real entries (FPF_TARGET=0.0).
Processed C02104658: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100564: 11 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104649: 21 real entries (FPF_TARGET=0.0).
Processed C02104984: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101490: 2 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100565: 22 real entries (FPF_TARGET=0.0).
Processed C01102305: 16 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03102826.parquet: No valid features generated for consumer C03102826
Processed C01101117: 15 real entries (FPF_TARGET=0.0).
Processed C01104731: 19 real entries (FPF_TARGET=0.0).
Processed C02103255: 15 real entries (FPF_TARGET=0.0).
Processed C04100497: 23 real entries (FPF_TARGET=0.0).
Processed C02104730: 10 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04101804: 18 real entries (FPF_TARGET=0.0).
Processed C01102315: 18 real entries (FPF_TARGET=0.0).
Processed C04103695: 20 real entries (FPF_TARGET=0.0).
Processed C02101106: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100575: 22 real entries (FPF_TARGET=0.0).
Processed C02101270: 7 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02101425: 15 real entries (FPF_TARGET=0.0).
Processed C01103767: 18 real entries (FPF_TARGET=0.0).
Processed C01101107: 19 real entries (FPF_TARGET=0.0).
Processed C02102304: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104721: 20 real entries (FPF_TARGET=0.0).
Processed C03102836: 18 real entries (FPF_TARGET=0.0).
Processed C04100487: 22 real entries (FPF_TARGET=0.0).
Processed C02103776: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102576: 24 real entries (FPF_TARGET=0.0).
Processed C04104929: 18 real entries (FPF_TARGET=0.0).
Processed C02102054: 19 real entries (FPF_TARGET=0.0).
Processed C01100316: 10 real entries (FPF_TARGET=0.0).
Processed C04102484: 22 real entries (FPF_TARGET=0.0).
Processed C02104648: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03100835: 16 real entries (FPF_TARGET=0.0).
Processed C02104460: 14 real entries (FPF_TARGET=0.0).
Processed C01103104: 18 real entries (FPF_TARGET=0.0).
Processed C02100602: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04104851: 24 real entries (FPF_TARGET=0.0).
Processed C01104142: 23 real entries (FPF_TARGET=0.0).
Processed C01101764: 25 real entries (FPF_TARGET=0.0).
Processed C04101686: 20 real entries (FPF_TARGET=0.0).
Processed C01100306: 19 real entries (FPF_TARGET=0.0).
Processed C02100612: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01102566: 20 real entries (FPF_TARGET=0.0).
Processed C04104939: 18 real entries (FPF_TARGET=0.0).
Processed C02100624: 15 real entries (FPF_TARGET=0.0).
Processed C02104456: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101774: 21 real entries (FPF_TARGET=0.0).
Processed C04102494: 19 real entries (FPF_TARGET=0.0).
Processed C01104152: 21 real entries (FPF_TARGET=0.0).
Processed C03100825: 16 real entries (FPF_TARGET=0.0).
Processed C02103410: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104213: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103114: 16 real entries (FPF_TARGET=0.0).
Processed C01103629: 22 real entries (FPF_TARGET=0.0).
Processed C02102627: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102601: 14 real entries (FPF_TARGET=0.0).
Processed C01101049: 22 real entries (FPF_TARGET=0.0).
Processed C03102978: 21 real entries (FPF_TARGET=0.0).
Processed C01100543: 19 real entries (FPF_TARGET=0.0).
Processed C03103493: 19 real entries (FPF_TARGET=0.0).
Processed C04101822: 22 real entries (FPF_TARGET=0.0).
Processed C02100057: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100119: 16 real entries (FPF_TARGET=0.0).
Processed C02103245: 14 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102199: 22 real entries (FPF_TARGET=0.0).
Processed C01103751: 12 real entries (FPF_TARGET=0.0).
Processed C02104235: 17 real entries (FPF_TARGET=0.0).
Processed C02102779: 14 real entries (FPF_TARGET=0.0).
Processed C01101131: 23 real entries (FPF_TARGET=0.0).
Processed C02101435: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02100880: 17 real entries (FPF_TARGET=0.0).
Processed C01104717: 25 real entries (FPF_TARGET=0.0).
Processed C03102968: 13 real entries (FPF_TARGET=0.0).
Processed C03102800: 20 real entries (FPF_TARGET=0.0).
Processed C01102333: 18 real entries (FPF_TARGET=0.0).
Processed C02100071: 20 real entries (FPF_TARGET=0.0).
Processed C01103639: 22 real entries (FPF_TARGET=0.0).
Processed C02102769: 12 real entries (FPF_TARGET=0.0).
Processed C01104659: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03102810: 2 real entries (FPF_TARGET=0.0).
Processed C02104470: 7 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101121: 22 real entries (FPF_TARGET=0.0).
Processed C01104707: 14 real entries (FPF_TARGET=0.0).
Processed C03103483: 5 real entries (FPF_TARGET=0.0).
Processed C02101403: 11 real entries (FPF_TARGET=0.0).
Processed C04101832: 24 real entries (FPF_TARGET=0.0).
Processed C03102189: 16 real entries (FPF_TARGET=0.0).
Processed C02100047: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100625: 18 real entries (FPF_TARGET=0.0).
Processed C04104583: 20 real entries (FPF_TARGET=0.0).
Processed C01104509: 23 real entries (FPF_TARGET=0.0).
Processed C02102567: 16 real entries (FPF_TARGET=0.0).
Processed C02103426: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102956: 12 real entries (FPF_TARGET=0.0).
Processed C03101974: 2 real entries (FPF_TARGET=0.0).
Processed C02100307: 13 real entries (FPF_TARGET=0.0).
Processed C03102387: 19 real entries (FPF_TARGET=0.0).
Processed C02103115: 18 real entries (FPF_TARGET=0.0).
Processed C01102045: 22 real entries (FPF_TARGET=0.0).
Processed C03101195: 21 real entries (FPF_TARGET=0.0).
Processed C01101257: 23 real entries (FPF_TARGET=0.0).
Processed C01103437: 15 real entries (FPF_TARGET=0.0).
Processed C02104508: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02102044: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101964: 13 real entries (FPF_TARGET=0.0).
Processed C01102055: 23 real entries (FPF_TARGET=0.0).
Processed C01104519: 21 real entries (FPF_TARGET=0.0).
Processed C02101256: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100635: 16 real entries (FPF_TARGET=0.0).
Processed C02100061: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102946: 23 real entries (FPF_TARGET=0.0).
Processed C01103427: 15 real entries (FPF_TARGET=0.0).
Processed C03101185: 19 real entries (FPF_TARGET=0.0).
Processed C01104461: 21 real entries (FPF_TARGET=0.0).
Processed C04101696: 22 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100070: 21 real entries (FPF_TARGET=0.0).
Processed C04104841: 21 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04100963: 19 real entries (FPF_TARGET=0.0).
Processed C02103263: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03104907: 10 real entries (FPF_TARGET=0.0).
Processed C01100108: 20 real entries (FPF_TARGET=0.0).
Processed C02101413: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01104224: 13 real entries (FPF_TARGET=0.0).
Processed C03103941: 6 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104225: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101402: 16 real entries (FPF_TARGET=0.0).
Processed C02100109: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01103262: 19 real entries (FPF_TARGET=0.0).
Processed C03103839: 29 real entries (FPF_TARGET=0.0).
Processed C01100891: 16 real entries (FPF_TARGET=0.0).
Processed C04103380: 9 real entries (FPF_TARGET=0.0).
Processed C01102768: 19 real entries (FPF_TARGET=0.0).
Processed C03104917: 21 real entries (FPF_TARGET=0.0).
Processed C02101048: 14 real entries (FPF_TARGET=0.0).
Processed C01102600: 18 real entries (FPF_TARGET=0.0).
Processed C01100060: 15 real entries (FPF_TARGET=0.0).
Processed C02100890: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103951: 1 real entries (FPF_TARGET=0.0).
Processed C02102611: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100881: 19 real entries (FPF_TARGET=0.0).
Processed C01102778: 13 real entries (FPF_TARGET=0.0).
Processed C02101130: 15 real entries (FPF_TARGET=0.0).
Processed C02101775: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01100118: 12 real entries (FPF_TARGET=0.0).
Processed C02100317: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103829: 21 real entries (FPF_TARGET=0.0).
Processed C04101498: 20 real entries (FPF_TARGET=0.0).
Processed C04102076: 23 real entries (FPF_TARGET=0.0).
Processed C03103634: 13 real entries (FPF_TARGET=0.0).
Processed C02103638: 13 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C01101396: 11 real entries (FPF_TARGET=0.0).
Processed C04100616: 16 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03101054.parquet: No valid features generated for consumer C03101054
Processed C03104672: 18 real entries (FPF_TARGET=0.0).
Processed C01102184: 5 real entries (FPF_TARGET=0.0).
Processed C02103835: 16 real entries (FPF_TARGET=0.0).
Processed C03102246: 15 real entries (FPF_TARGET=0.0).
Processed C04101264: 19 real entries (FPF_TARGET=0.0).
Processed C03100426: 19 real entries (FPF_TARGET=0.0).
Processed C02104153: 18 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02104873: 14 real entries (FPF_TARGET=0.0).
Processed C04104442: 17 real entries (FPF_TARGET=0.0).
Processed C01101386: 14 real entries (FPF_TARGET=0.0).
Processed C01102975: 19 real entries (FPF_TARGET=0.0).
Processed C03101044: 20 real entries (FPF_TARGET=0.0).
Processed C04100606: 26 real entries (FPF_TARGET=0.0).
Processed C04102066: 22 real entries (FPF_TARGET=0.0).
Processed C03103624: 17 real entries (FPF_TARGET=0.0).
Processed C02102577: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04102887: 19 real entries (FPF_TARGET=0.0).
Processed C04104452: 23 real entries (FPF_TARGET=0.0).
Processed C04103414: 22 real entries (FPF_TARGET=0.0).
Processed C03102256: 14 real entries (FPF_TARGET=0.0).
Processed C02102332: 17 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03103061: 14 real entries (FPF_TARGET=0.0).
Processed C04102623: 21 real entries (FPF_TARGET=0.0).
Processed C01100950: 5 real entries (FPF_TARGET=0.0).
Processed C04103329: 25 real entries (FPF_TARGET=0.0).
Processed C04101549: 14 real entries (FPF_TARGET=0.0).
Processed C03104027: 3 real entries (FPF_TARGET=0.0).
Processed C02101058: 16 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C02103628: 12 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C03101601: 17 real entries (FPF_TARGET=0.0).
Processed C04100043: 10 real entries (FPF_TARGET=0.0).
Processed C03103119: 3 real entries (FPF_TARGET=0.0).
Processed C03102413: 2 real entries (FPF_TARGET=0.0).
Processed C01100828: 19 real entries (FPF_TARGET=0.0).
Processed C02103740: 15 real entries and 20 simulations (FPF_TARGET=1.0).
Processed C04103251: 25 real entries (FPF_TARGET=0.0).
Processed C02101800: 18 real entries (FPF_TARGET=0.0).
Processed C03103880: 17 real entries (FPF_TARGET=0.0).
Processed C04101431: 17 real entries (FPF_TARGET=0.0).
Processed C03101779: 9 real entries (FPF_TARGET=0.0).
Processed C04104217: 17 real entries (FPF_TARGET=0.0).
Error processing /Users/jasonc/Desktop/DSC_291/split_transactions/C03104037.parquet: No valid features generated for consumer C03104037
Processed C04101559: 21 real entries (FPF_TARGET=0.0).

In [10]:
output_df

,dominant_freq_cat0.0,dominant_power_cat0.0,spectral_entropy_cat0.0,low_freq_power_cat0.0,high_freq_power_cat0.0,power_ratio_cat0.0,masked_consumer_id,FPF_TARGET,dominant_freq_cat1.0,dominant_power_cat1.0,...,spectral_entropy_cat33.0,low_freq_power_cat33.0,high_freq_power_cat33.0,power_ratio_cat33.0,dominant_freq_cat31.0,dominant_power_cat31.0,spectral_entropy_cat31.0,low_freq_power_cat31.0,high_freq_power_cat31.0,power_ratio_cat31.0
0,0.125000,3.854318e+05,1.052376,0.000000e+00,3.125031e+05,0.000000,C03104658,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,C03104658,0.0,0.090909,9.459581e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,C03104658,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,C03104658,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,C03104658,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320480,0.044444,1.097864e+08,2.626234,1.959586e+08,1.137464e+08,1.722768,C04101672_simulate_16,1.0,0.020833,7.045531e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320481,0.044444,1.157732e+08,2.546525,2.218033e+08,1.199431e+08,1.849238,C04101672_simulate_17,1.0,0.020833,6.045486e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320482,0.044444,1.110504e+08,2.584032,2.019182e+08,1.122327e+08,1.799104,C04101672_simulate_18,1.0,0.020833,6.094634e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320483,0.044444,1.158226e+08,2.525013,2.141036e+08,1.186630e+08,1.804300,C04101672_simulate_19,1.0,0.020833,6.738675e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320484,0.044444,1.095160e+08,2.586120,2.101894e+08,1.058120e+08,1.986443,C04101672_simulate_20,1.0,0.020833,6.227035e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Sort by FPF_TARGET and set masked_consumer_id as the index
output_df_sorted = output_df.sort_values(by='FPF_TARGET')
output_df_sorted = output_df_sorted[sorted(output_df_sorted.columns)]

In [12]:
output_df_sorted = output_df_sorted.fillna(0)
output_df_sorted = output_df_sorted.set_index('masked_consumer_id')
output_df_sorted.to_csv("/Users/jasonc/Desktop/DSC_291/processed_data.csv")

In [13]:
output_df_sorted

,FPF_TARGET,dominant_freq_cat0.0,dominant_freq_cat1.0,dominant_freq_cat10.0,dominant_freq_cat11.0,dominant_freq_cat12.0,dominant_freq_cat13.0,dominant_freq_cat14.0,dominant_freq_cat15.0,dominant_freq_cat16.0,...,spectral_entropy_cat32.0,spectral_entropy_cat33.0,spectral_entropy_cat34.0,spectral_entropy_cat35.0,spectral_entropy_cat4.0,spectral_entropy_cat5.0,spectral_entropy_cat6.0,spectral_entropy_cat7.0,spectral_entropy_cat8.0,spectral_entropy_cat9.0
masked_consumer_id,,,,,,,,,,,,,,,,,,,,,
C03104658,0.0,0.125000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
C03100527,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
C03100527,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.0,1.855205,0.000000,0.000000,0.0,0.0,0.0
C03100527,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,2.920440,0.000000,0.0,0.0,0.0
C03100527,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,3.296088,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C02103537_simulate_14,1.0,0.142857,0.086957,0.0,0.0,0.312500,0.000000,0.052632,0.000000,0.045455,...,0.0,0.0,0.000000,0.0,0.000000,0.866018,0.000000,0.0,0.0,0.0
C02103537_simulate_13,1.0,0.428571,0.130435,0.0,0.0,0.312500,0.000000,0.052632,0.000000,0.136364,...,0.0,0.0,0.000000,0.0,0.000000,0.670696,0.000000,0.0,0.0,0.0
C02103537_simulate_12,1.0,0.476190,0.086957,0.0,0.0,0.250000,0.000000,0.052632,0.000000,0.045455,...,0.0,0.0,0.000000,0.0,0.000000,0.787734,0.000000,0.0,0.0,0.0
C02103537_simulate_10,1.0,0.142857,0.130435,0.0,0.0,0.250000,0.000000,0.052632,0.000000,0.045455,...,0.0,0.0,0.000000,0.0,0.000000,0.829017,0.000000,0.0,0.0,0.0
C04101672_simulate_20,1.0,0.044444,0.020833,0.0,0.0,0.166667,0.085106,0.478261,0.234043,0.282609,...,0.0,0.0,2.824001,0.0,2.531131,2.226926,3.072848,0.0,0.0,0.0

In [14]:
# Group by customer_category and FPF_TARGET, then count occurrences
category_target_counts = (
    output_df_sorted["FPF_TARGET"].value_counts()
)

In [15]:
category_target_counts

0.0    234575
1.0     85910
Name: FPF_TARGET, dtype: int64